let array = [
"4000 zombies nous contemplent",
"5e roue du carrosse",
"Où est Larchi ?",
"Une caravane sans roues ???",
"Une fissure ? Quelle fissure ?",
"Une lettre sans adresse",
"Poches bien rangées",
"Un vrai jeu denfants !",
"Chantier à labandon",
"Parc à labandon",
"Puits abandonné",
"Abattoir",
"Panique",
"Absinthe toi la prochaine fois",
"Charlatan diplômé",
"As",
"Projection acide",
"Clé à Molette",
"Maître Es-thète",
"Citoyen agressif !",
"Roquettes",
"Alcools",
"Monte-en-lair",
"Dernière chance",
"Jusquau bout, et même un peu moins loin",
"Messie",
"Briqueteur conscienceux",
"Eeeeeeeet ben non",
"{ref__icu, select,\n on {\n {ref__gender, select,\n female {Seule au monde...}\n other {Seul au monde...}\n }\n }\n other {Seul(e) au monde...}\n }",
"Autel de la rédemption",
"Laborantin amateur",
"Ambulance",
"Amophilis psychotropes",
"Ampère et contre tous",
"Stéroïdes Anabolisants",
"Le 7ème jour, il créa la cage à viande",
"Enclos",
"Défunt animé",
"Chaîne Hi-Fi défensive",
"Badge de Shérif",
"Refouleur de macchabées",
"Pomme",
"Pommier de lOutre-Monde",
"1er Avril",
"Aqua-Splash",
"Forçat du désert",
"Architecte",
"Architectoire",
"Coffre darchitecte",
"Maitre rôliste",
"Quand est ce quon arrive ?",
"Armageddon",
"Boîte-déjeuner",
"Témoin de lArmageddon",
"Cloison en bois",
"Cloison métallique",
"Cloison épaisse",
"Bras",
"Avant-poste militaire",
"Fripouille",
"Fusil dassaut",
"Mort par latome",
"Appelez-moi Maîtresse",
"Piston verrou",
"Arroseurs auto",
"Indésirable autonome",
"Victoire en tant quApprivoiseur lors du Choc des Héros !",
"Jai froid, dehors...",
"Sac de ciment",
"Sac dherbe fraîche",
"Appâts",
"Bandage rudimentaire",
"Bannissements",
"Note dun citoyen banni",
"Barbelés",
"Barney Gumble de lOutre-Monde",
"Pile",
"Lance-Pile 1-PDTG",
"Super lance-piles",
"Chemin de ronde",
"Michel Fugueur",
"Lampe de chevet éteinte",
"Réfrigérateur détudiant",
"Chope de bière",
"Cadavre débutant",
"Courroie",
"Compilation du King",
"Betapropine 5mg",
"Fouineur de décharge",
"Oiseau de mauvais augure",
"Suintement cervical noir",
"Bloque les chantiers",
"Route barrée",
"Vomisseur de tripes",
"Pansement ensanglanté",
"Café brûlant",
"Cracheur de flamme bleue",
"Captain Parpaing",
"Sorteur en chef",
"Vaporisateur",
"Dynamitage",
"Feu de joie",
"Deux yeux ouverts",
"Décapsuleur",
"Empreinte de décapsuleur",
"Cutter",
"Caisse de feux dartifice",
"Boîte de jeu",
"Boîte dallumettes",
"Cartons",
"Prospecteur courageux",
"Gloire au PMV !",
"Passage en Force",
"Maladresses",
"Armoire à glace",
"Fais de moi ton objet",
"CD de Britney Spears",
"Appareil électronique en panne",
"Scie à métaux abimée",
"Os humain fêlé",
"Bâton cassé",
"Char dassaut en panne",
"Camaraderie",
"Bruce Campbell",
"Le Bruce Lee de la truelle",
"Canon brutal",
"Bouddha",
"Bâtisseur",
"Stratégies citoyennes",
"Registre chantier",
"Réparations de chantiers",
"Clé à percussion",
"Empreinte de clé à percussion",
"Plan de chantier (rare)",
"Plan de chantier (inhabituel)",
"Plan de chantier (très rare !)",
"Bâtiment non déterré",
"Boussole sur patte",
"Brûlez-le, voyez si ses cendres deviennent vertes!",
"Pointeur laser brûlant",
"Chamallows calcinés",
"Torche consumée",
"Ecole maternelle brûlée",
"Boucherie",
"Cafetière",
"Tenue de camouflage",
"Lit de camp",
"Camping",
"Boîte de conserve",
"Ouvre-boîte",
"Cannibalisme",
"Monticules canons",
"Cuistot de cantine",
"Capitaine Crochet",
"Portière de voiture",
"Four cancérigène",
"Citrouille molle sculptée",
"Adepte SM",
"Catapulte Primitive",
"Caverne",
"Ciment & Garfunkel",
"Cantine centrale",
"Laboratoire central",
"Aborigène curieux",
"Tronçonneuse",
"Massacre à la tronçonneuse",
"Tronçonneuses",
"Héros du peuple",
"Donateur universel",
"Che Guevara du désert",
"Vaincre la mort",
"Exhumeur de babioles",
"Dévoreur de citoyens",
"Coffre",
"Poule",
"Joindre linutile à lagréable",
"Nouilles chinoises",
"Crapule",
"Croix en Chocolat",
"Bûche de Noël",
"Noël",
"Bonbon de Noël",
"Caisse surprise",
"Figurine de Chuck",
"Le Tueur",
"Cinéma",
"Habitant",
"Trafiquant de citoyens",
"Citoyens",
"Maison dun citoyen",
"Tente dun citoyen",
"Affaires dun citoyen",
"Clairvoyance",
"PDG du Choc",
"Mort Ultime du CDH",
"Organisation du Choc",
"Titan du Choc",
"Mine Antipersonnelle",
"Clair(e)",
"Arsène Lupin du désert",
"Serrez les rangs... et les fesses...",
"fermé",
"Trèfle",
"Cercueils sur ressort",
"Mine effondrée",
"Carrière effondrée",
"Fan des X-men",
"Petit chef cuistot",
"Médailles communautaires",
"Compagnon de la communauté",
"Extrémiste communautaire",
"Quartiers circulaires",
"Animé de bonnes intentions",
"Hyper-activiste communautaire",
"Détonateur compact",
"Jai la dé-dale !",
"Plaintes",
"Bétonnade",
"Plan de chantier (commun)",
"Plan de chantier (rare)",
"Plan de chantier (inhabituel)",
"Plan de chantier (très rare !)",
"Carton de matériaux",
"Abri de chantier",
"Chantiers",
"Chantiers",
"Lentille convexe",
"Tube de cuivre",
"Coquet",
"Chimiste du coin",
"Eboueur",
"Exterminateur",
"Produit corrosif",
"Spécialiste ès corvidés",
"Laboratoire cosmétique",
"Parrain cosmique",
"Ouverture de porte",
"Artisanat",
"Morceau de caisse",
"Crémato-Cue",
"Corbeau lutin",
"Guirlande de Corbeaux",
"Statue du Corbeau",
"Copain des corbeaux",
"Tour des éclaireurs",
"Crucifixion",
"Pile broyée",
"Lecteur curieux",
"Teddy nOurs maudit",
"Chaine Hifi maudite",
"Cyanure",
"Increvable",
"Danse avec les zombies",
"Maître cambrioleur",
"Campeur téméraire",
"Petit bois obscur",
"Jour",
"Lanterne de jour",
"Morts dans votre lit",
"Dentiste serrurier",
"Morts par Déshydratation",
"Morts par Infection",
"Morts par Manque",
"Rideau",
"Illustre vétéran",
"Décoration",
"Décharge blindée",
"Défenseur",
"Fixations de défenses",
"Supports défensifs",
"Concitoyen déshydraté",
"Déshydraté(e)",
"Maître doeuvre dément",
"Cordon bleu du village",
"Zone épuisée",
"Villa délabrée",
"Descendant des atlantes",
"Historien du désert",
"Orphelin du désert",
"Taupe géante",
"Champollion du désert",
"Forain de lOutre Monde !",
"Spéculateur du désert",
"Gare de triage désertée",
"Pharmacie détruite",
"Devastator (vide)",
"Devastator incomplet",
"Devastator (chargé)",
"Sans Foie ni Loi",
"Carreau",
"Dés",
"Dictateur",
"Immeuble délabré",
"Uniforme de citoyen sale",
"Tondeuse démontée",
"Explorations avancées",
"Région éloignée",
"Carcasses de voitures",
"Silos à labandon",
"Recycleur dâmes",
"Âme divine",
"Roquette Foreuse",
"Détecteur à eau",
"Maître du coup de bol",
"Plat fait-maison douteux",
"Ça se fume ? cest de moi.",
"La patée, cest pas si mauvais",
"Doggy-bag",
"Labyrinthe master MB",
"Collectionneur de vie",
"Je ne rentrerai pas ce soir...",
"Zavez pas mieux à faire ?",
"Paillasson",
"Explorateur impétueux",
"Fan dHannibal",
"Chewing-gums séchés",
"Chamallows séchés",
"Foreuse puits",
"Boire",
"Expérimentations",
"Drogué(e)",
"Bichon maltais shooté",
"Drogues",
"Ivre",
"Rustine",
"Villa de Duke",
"Décharge",
"Décharge humidifiée",
"Enquiquineur débrouillard",
"Ranger du risque",
"Livre poussiéreux",
"Boules Quies",
"lest",
"Pâques",
"Oeuf de Pâques",
"Projet Eden",
"Edit Piaf",
"Œuf",
"Chaise Ektörp-Gluten",
"Batteur électrique",
"Composant électronique",
"Banni émancipé",
"Dispositifs durgence",
"Bidon dhuile vide",
"Distributeur vide",
"Sport-élec",
"Une encyclopédie",
"Moteur",
"Édificateur illuminé",
"Prêcheur illuminé",
"Une enveloppe",
"Égal de Chuck Norris",
"Tranchée aménagée",
"Claviceps Purpurea",
"Cidre Claviceps Artisanal",
"Escorte",
"Éternel second",
"Tout pour ma gueule",
"Muraille évolutive",
"Déblaiement",
"Consomme trop deau",
"Fatigué(e)",
"Fatigué(e)",
"Expéditionnaire au long cours",
"Explorations très lointaines",
"Pamplemousse explosif",
"Bombe à eau explosive",
"Mutilateur",
"Lamour extra large",
"Citoyen hors-norme",
"Bastion",
"Cuisine exotique",
"Explorateur vraiment impétueux",
"Projets insensés",
"Oeil",
"Lœil du désert",
"Manufacture",
"Stand de fête foraine",
"Double fond",
"Fausse Ville",
"Caveau familial",
"Fast-Food",
"Gros chat mignon",
"Serpent agonisant",
"Le Père Noël est un coquin",
"Le Père Noël est une ordure",
"Robinetterie",
"Roue de Grostas",
"Aventurier sans peur",
"Rassasié(e)",
"Clôture",
"Fertilisation sauvage",
"Pelures de peau",
"Combats désespérés",
"Remplir",
"Feux dartifices",
"Tube de lancement Floush",
"Maître ingénieur",
"Chair à canon du FJV08",
"Bombe Pulvérine",
"Poudre-comète brute",
"Meuble en kit",
"Senfuir",
"Coyote des steppes arides",
"Purée de charognardes",
"Charognardes",
"Appâts odorants",
"Caisse de nourriture",
"Pied",
"Habitations fortifiées",
"Bonnet rouge malodorant",
"Costume malodorant dune autre époque",
"Fondations",
"Fondateur du temps perdu",
"Kebab « Chez Coluche »",
"La Bamba",
"Citoyen libre !",
"Décharge organisée",
"Négociant en chair fraîche",
"Hermitamor",
"Ingénieur complètement givré",
"Jerrycan",
"Le plein de Protéines.",
"Détourneur de fonds",
"Petit chaton furieux",
"Potence",
"Décharge publique",
"Cabane de jardin",
"Neurotoxine",
"Gazette",
"Traqueur de geeks",
"Générosité",
"Gentleman Cambrioleur",
"Une rustine et ça repart.",
"Goule",
"Sérum pour Goule",
"PMV géant",
"Rat géant",
"Château de sable",
"Colis de Noël",
"A boire ou jtue le chien !",
"Gloire",
"Gloire au Corbeau !",
"Cadavre rongé",
"Jaime les bandes décimées",
"Riche gourou",
"Mouilleur de cadavres",
"Pilleur de tombeau",
"Good Guy",
"Citoyen de bon goût",
"Maître des clés",
"Pamplemousses explosifs",
"Muraille rasoir",
"Grand architecte",
"Grand Ermite indépendant",
"Franc-maçon",
"Douves",
"Grand Fossé",
"Grand créateur tout-puissant",
"Bière",
"Costume de Lutin Vert",
"Bombe macabre",
"Toile de tente",
"Chien hargneux (alias Pepette)",
"Garde des seaux",
"Tour des gardiens",
"Gardien",
"Gardien gagnant du CDH",
"Guérilla",
"Guide de lOutre-Monde",
"Cobaye de laboratoire",
"Armurerie GunsnZombies",
"Spécialiste en pistolets à eau",
"Scie à métaux",
"Ailerons de poulet entamés",
"Halloween",
"Hamâme",
"Main",
"Poignée de cartouches",
"Poignée de vis et écrous",
"Poignée de bonbons",
"Clé à molette de compet",
"Pendaisons",
"Bonheur de magnitude 8",
"Bien dans sa peau",
"Hamster jovial",
"Annonciateur du fléau",
"Pandémonium mon amour!",
"Le Pandémonium ? Pff. Easy.",
"Cocodile dundee",
"Bureau monté à la rache",
"Vous avez du feu ?",
"Il était un foie...",
"Tête",
"Chef-Pelleteur",
"Convalescent(e)",
"Corps sain",
"Cœur",
"Lenfer, cest mon quotidien.",
"Lenfer, jen mange un peu chaque matin",
"Vous êtes là les copains?",
"Poulailler",
"Héros",
"Le mot des héros",
"Actions héroïques",
"Retour du Héros",
"Coucou! Tu veux voir ma pile ?",
"Grande prêtresse du temple du soleil",
"Joueur très expérimenté",
"Tenez vos positions !",
"Cannibales Holocauste",
"Holy F***ing Iceberg",
"Pluie bénite",
"Ma Maison",
"Bricotout",
"Bricoleur du dimanche",
"Améliorations de maison",
"Cave laboratoire",
"Travaux chez soi",
"Bichon-Garou susceptible",
"Dépendant(e)",
"Au-delà du réel",
"Plan de chantier (rare)",
"Plan de chantier (inhabituel)",
"Plan de chantier (très rare !)",
"Montgolfière",
"Plan de chantier (rare)",
"Plan de chantier (inhabituel)",
"Plan de chantier (très rare !)",
"Maison",
"Taudis",
"Une petite tranche de Vachette ?",
"Serpent de 2 mètres",
"Viande humaine",
"Hundesteaks: Responsable dextinctions",
"Gueule de bois",
"Chacal affamé",
"Crosse de Hockey",
"Hydratone 100mg",
"Réseau hydraulique",
"Ingénierie hydraulique",
"Faucheur de loutre-monde",
"Je suis une bête !",
"Chef-Ascète",
"Je suis une légende.",
"Crrrooaaââ !",
"Archi-maid illustrateur de Pi",
"Oh on voit les zombies dici",
"Je nai besoin de personne",
"Rien ne méchappe.",
"Je mâche le silex !",
"Jai un plan",
"Je sais, jai un grain",
"Je vois des morts partout",
"I see dead people 0_0",
"Je goûte tous mes produits",
"Disciple de Garrett",
"Je marche seul.",
"Allergique à la ville",
"Jai fait le tour du monde... 2 fois !",
"Jai même fouillé les WC !",
"Jai mal au ventre...",
"Une BMW ? Pas de poblème !",
"Avant 55°, cest de leau",
"Spécialité : steak de chaton",
"Suis-moi si tu veux vivre",
"Bricol girl travesti",
"Carnet illisible",
"Guide éclairé",
"Im a believer",
"Lincroyable citoyen",
"Jai le vertige",
"Labbé Tonière",
"Immunisé(e)",
"Paillasson piégé",
"Dedans jusquau cou !",
"Ancien bêta-testeur",
"Cafetière incomplète",
"Tronçonneuse incomplète",
"Jeu de cartes incomplet",
"Incroyable détermination",
"Cimetière indien",
"Creuseur de grands trous",
"Indiana jones et les ruines de loutre-monde",
"Infecté(e)",
"Porteur de la Maladie",
"Infirmerie",
"Blessures",
"Seconde couche",
"Insatiable citoyen",
"Inspiration pour le peuple",
"Manuel dinstructions",
"Insulte ou comportement",
"Citoyen infranchissable",
"Architecte dintérieur",
"Internet Explorer",
"Melon dintestin",
"Les poches irlandaises sont blindées!",
"Cantine en fer",
"Cest un oiseau, cest un avion? Non cest super lance pile",
"La mort a peur de moi !",
"Ça faisait plus petit sur le catalogue",
"Cest meilleur si ça hurle.",
"Cétait vraiment trop facile.",
"Valet",
"Gontran Bonheur",
"Table Järpen",
"Le Pacificateur",
"Pompe à Jerrycan",
"Juste un doigt !",
"Exemple pour la jeunesse",
"Kalachnikeau",
"Septicis-mite aïgu",
"Gardien des plaisirs",
"Garde trop de choses pour lui",
"Un ptit Bricard ?",
"Roi",
"Cuisine",
"BricoFacile",
"Expérience dangereuse",
"Une étiquette",
"Ouvrier",
"Labyrinthe",
"Gollum des labyrinthes",
"Grand coffre",
"Gros rideau",
"Gros colis postal",
"Gros coffre en métal",
"Diode laser",
"Dernier rempart",
"Last man standing",
"Dernière ligne",
"Mort Ultime",
"Mort Ultime du Pandémonium !",
"Piston calibré",
"Tondeuse à gazon",
"Colmateur de fuite",
"Campeur avisé",
"Jambe",
"Maître-bichon",
"Légende de lOutre-Monde",
"Apprivoiseur légendaire",
"Ville légendaire !",
"Gardien des archives",
"Lumière dans la nuit",
"Phare",
"Écoutez ma voix",
"Citrouille allumée",
"Livre zen miniature",
"30 millions dennemis",
"Dealer du village",
"Verrou",
"Im a poor lonesome hermit...",
"Longue Vue",
"Supermarché pillé",
"Âme errante",
"Messie du monde perdu",
"Love Gourou",
"réduites",
"LSD",
"Partenaire de danse de Lucifer",
"Chanceux",
"Lucky 7",
"Trouvaille (améliorée)",
"Croque morts",
"Mac Gyver de lOutre-Monde",
"Coupe-Coupe",
"Atomic Café",
"Clé magnétique",
"Empreinte de clé magnétique",
"Purifier la zone",
"Barricades à clouer",
"Guitare artisanale",
"Fais bouger les choses!",
"Grand pâtissier du désert",
"Une fois, au stage dété...",
"Sac supplémentaire",
"Manipulateur",
"Carte",
"Top-Chef de loutre-monde",
"Maître-décorateur de tentes",
"Martine à la plage",
"Masochisme",
"Maître-architecte",
"Grand bâtisseur",
"Cooking-mama",
"Maître gardien",
"Maître de linutilité",
"Maître dégoteur",
"Maître Dénicheur",
"Passe-muraille",
"Chef doeuvre en péril",
"Matelas",
"Maire",
"Seul(e) contre les Hordes",
"Cage à viande",
"Amateur de viande humaine",
"Os charnu",
"Derrick",
"Mécanisme",
"Membre de la Croix Rouge",
"Mémoire de la civilisation",
"Messages",
"Boîte en métal",
"Ferraillerie",
"Poutres renfort",
"Structures métalliques",
"Champ mines eau",
"Petite chaîne Hi-Fi",
"Mini-market",
"Armurerie",
"Ne participe quasiment pas",
"Bureau des esclavagistes",
"Pluvio-canons",
"Téléphone portable",
"Obélisque des temps modernes !",
"Money for Nothing",
"Randonneur égaré",
"Rangements",
"Motel Dusk",
"Festivalier hordien motivé",
"Relais autoroutier",
"Jambon-beurre moisi",
"Napolitains moisis",
"Mont pointu",
"Scribe motivé",
"Grosse brute",
"Mon nom est personne",
"Mysticisme",
"Potion chamanique",
"Transformation mystique",
"Mythe vivant",
"Neil Armstrong de lOutre Monde",
"Désherbant Ness-Quick",
"Reste toujours au chaud",
"Je touche pas à ça, MOI.",
"Jamais sans mon seau",
"Nuits dans le désert",
"Foreuse améliorée",
"Âme noble",
"Âme digne",
"Bâtisseur du non-sens",
"le nord",
"le nord-est",
"le nord-ouest",
"Même pas peur !",
"Jamais sans mon chien !",
"Maglite PifGadget",
"Abri anti-atomique",
"Leerdâmeur nauséabond",
"Objets",
"Ancien aérodrome",
"Ancien Velib",
"Vieille porte",
"Vieil hôpital de campagne",
"Vieille Pompe Hydraulique",
"Ancien commissariat",
"Le Père Noël est une ordure",
"Vieille machine à laver",
"Oubliettes",
"Omniscience",
"Cache de contrebandiers",
"Un Oeil ouvert",
"Restera dans les annales",
"Une ville pour les gouverner tous!",
"Boîte de conserve ouverte",
"Open-chakra",
"ouvert",
"Paquet de cigarettes entamé",
"Pims périmé",
"Paquet de chips molles",
"Chaîne de Porte + cadenas",
"Château",
"Pandémonium",
"Paracétoïde 7g",
"Parano",
"Un colis",
"Partiellement putréfié",
"Ville participante",
"Patch-day, no-play",
"Poutre rafistolée",
"Canif dérisoire",
"Unité centrale",
"Dictature des héros",
"Membre permanent du club Mickey",
"Tapis persan",
"Produits Pharmaceutiques",
"CD de Phil Collins",
"Phoenix des hôtes de ces bois",
"Album photo",
"Meubles Kiela",
"Pigeon de lOutre-Monde",
"Pilier de comptoir",
"Pillard",
"Pillages de maison",
"Référence communautaire",
"Fumigène enteur Sapin",
"Piège à loups",
"Carlingue davion",
"Sac plastique",
"Sac plastique + explosif",
"Lance-Grenailles",
"Pasteur du village",
"Vautour",
"Contre-plaqué",
"Compagnon de poche",
"Petit manche vibrant",
"Portail",
"Bureau de poste",
"Ecumeur post-mortem",
"Petit préparateur",
"Lambeau de chair",
"Âme forte",
"Appareil photo davant-guerre",
"Planificateur",
"Pendez le Père Noël !",
"Bretzel",
"Camé prévoyant",
"Ville privée",
"Campeur professionnel",
"Veilleur Pro",
"Prodige",
"Orfèvre gobeur",
"Testeur de produits",
"Métier",
"Discours rassurant multicoloré",
"Médium au rabais",
"Éclairage public",
"Expert de la cuillère",
"Pompe",
"Eau croupie purifiée",
"Calibrateur PDTT Mark II",
"Le travail, cest la santé",
"Buche en bon état",
"Dame",
"Citoyen rayonnant",
"Radio K7",
"RadioactiveMan",
"Radius Mark II",
"Balise Radius",
"Perforeuse",
"Ancêtre de Rambo",
"Chef-Rempart",
"Petits beurres rances",
"Ville classée",
"Grand Mange-vermines",
"Réacteur soviétique",
"Recycler la maison",
"Actualiser",
"Désaltéré",
"Abonné au sauna du pandémonium",
"Apnéiste confirmé",
"Réincarnator",
"Blindage dentrée",
"Renforts",
"Sorteur",
"Grand rénovateur",
"Kit de bricolage",
"Réparations",
"Sauvetage",
"Débrouillardise",
"Revolver",
"Bouclier Anti-émeutes",
"Pantalon rouge déchiré",
"Canon à briques",
"Chaîne HI-FI Rock nRoll",
"Rocking Chair",
"Rôliste",
"mode apprentissage",
"Souche de bois pourrie",
"Tas détritus",
"Sac à dos",
"Alarme rudimentaire",
"Bâtiment",
"Exploration de ruine",
"Découvreur de bâtiments",
"Grosse chaîne rouillée",
"Voleur",
"Sabotage dexpéditions",
"Coffre-fort",
"Maison clôturée",
"Citoyen qui tombe à pic",
"Boule de sable",
"Boules de sable !",
"Fantôme des sables",
"Ouvrier des sables",
"Château de sable",
"Ensableur",
"Franc-tireur sablonneux",
"Sanibroyeur",
"Le Père Noël est une raclure",
"Le Père Noël est un filou",
"Renne du papa noyel",
"Sauveur de lhumanité",
"Steak de sciure",
"Scanner",
"Champs dépouvantails",
"Fouineur",
"Fouineur gagnant du CDH",
"Boîte de Schrödinger",
"Epicerie Fargo",
"Fléau du monde animal",
"Éclaireur",
"Débris métalliques",
"Réveil-Hurleur",
"Scies hurlantes",
"Tournevis",
"Feuille raccornie",
"Coffre darchitecte scellé",
"Fouiller les déchets",
"Scrutateur",
"Prévoyant",
"Second souffle",
"Second souffle",
"Veste rouge usée",
"Membre de la secte",
"Trouvaille",
"Joue trop perso",
"Explosifs bruts",
"Couteau à dents",
"Sésame, bouge ton c...",
"Baraque",
"Maître des ombres",
"Bar miteux",
"Chaman",
"Plaque de tôle",
"Fragments de tôle",
"Morceau de contreplaqué",
"Cerbère de la porte",
"Choc des héros",
"Tourelle lance-eau",
"Caddie",
"Douches",
"Réserves dun citoyen avisé",
"Banni",
"Coin sieste",
"Grand arroseur",
"Chef de chantier",
"Mur Savonné",
"Caniveaux",
"Cantine à bois",
"Cimetière cadenassé",
"Palissade",
"Petite maison",
"Petite Pelle",
"Petite carte",
"Lance-bête",
"De la fumée ? Quelle fumée ?",
"Marchand de sable",
"Si jaurais su, jaurais po vnu",
"Bah alors on nattend pas Patrick ?",
"Animal social",
"Assistant social",
"Citrouille molle",
"Notaire de loutre-monde",
"Plaque de bois solide",
"Agnos-tic",
"Collecteur dâmes",
"Maçon du coeur",
"Âme du professionnel",
"Purificateur dâmes",
"Aruspice maudit",
"Marchand dâmes",
"Spider-Ame",
"le sud",
"le sud-est",
"le sud-ouest",
"Porteur du Souvenir",
"Pique",
"Nuchuk à molette",
"Nouilles chinoises épicées",
"Fosse à Pieux",
"Muraille à pointes",
"Champs piégés",
"Mirage Spirituel",
"Guide Spirituel",
"Arroseur",
"Fusée éclairante",
"St. Patrick",
"Pile de feuilles",
"Grand Bâton Sec",
"Eau croupie",
"Lance-pieu",
"Biscuit fade",
"Vibrant hommage",
"Statue du Corbeau",
"Boule de pâtes visqueuse",
"Expulseur de cadavres",
"Cochon malodorant",
"Conteur dhistoires",
"Un étrange appareil circulaire",
"Epices fortes",
"Abri fortifié",
"Plus belle la vie !",
"Dormeur suicidaire",
"Pistolereau",
"Poudre Super-Fuzz",
"Super-Héros en devenir",
"Livre de survie",
"Ermite",
"Ermite gagnant du CDH",
"Survivant de lenfer !",
"Jus de mirabelle suspect",
"Légume suspect",
"Magasin suédois",
"Vengeance sordide",
"Couteau suisse",
"Guillotine à Bokor",
"Ami des bêtes",
"Apprivoiseur",
"Taser dauto-défense",
"Bons ptits plats",
"Bon plat fait-maison",
"Steak appétissant",
"Plus fort que Sam Fisher",
"Routier du rhum",
"Petite frappe",
"Technicien",
"TechnicoMecanoMegalo",
"Teddy nOurs",
"Téléscope",
"Tente",
"Loutre-monde est mon bac à sable",
"Spécialiste en terraformation",
"Terrorisé(e)",
"Ça tiendra encore 10 ans !",
"Banque",
"Cétait pas ma guerre",
"Grand déménagement",
"Amateur du PMV tournevis",
"Redresseur de Pise",
"Chapeau moellon et bottes de cuivre",
"La garde meurt, mais ne se rend pas !",
"Broyeur de cadavres",
"Colonie de fourmis humaine",
"Lady in Red",
"Le dernier survivant",
"Camion « Mairie-mobile »",
"Spécialiste en aubaine",
"Total annihilation",
"Le Roc !",
"Lavant-dernier des Mohicans",
"Le bar des illusions perdues",
"Je vois une Vallée Bleuûuue !",
"Furtif",
"Il est venu le temps des cathédrales",
"La vérité est ailleurs",
"Puits",
"Nombreux vols dobjets",
"Larcins",
"Débiteur de viande",
"Gardien de la Pile",
"Jai donné mon nom à une constellation",
"Substance épaisse",
"Troisième couche",
"Soif",
"Ce lutin est imparable!",
"Mille et une vie",
"MuadDib",
"Bichon maltais à 3 pattes",
"Fan-tomme rapé",
"Bichon maltais fatigué",
"Constructeur increvable",
"Vers linfini et au-delà !",
"Enterré volontaire",
"Outils en vrac",
"Caisse de matériel",
"Torche",
"Âme torturée",
"Tour",
"Ville",
"Bibliothèque de quartier",
"Créateur de villes",
"Plâtrier de la ville",
"Uniforme de citoyen",
"Les évolutions du jour",
"Toxine",
"Cadavre dun voyageur",
"Perfidie",
"Tréteau",
"Concitoyen de confiance",
"Voyageur téméraire",
"Twinoïde 500mg",
"La twinoïde, cest tabou",
"Planche tordue",
"Rencontre du 4ème type",
"Aware",
"Grogro mur",
"Promeneur désespéré",
"Ultime explorateur Hordien",
"Trouveur en chef",
"Sac super-pratique",
"Indécis",
"Maître pâtissier du désert",
"Médicament sans étiquette",
"Débris méconnaissables",
"Campeur inébranlable",
"Pavés de béton informes",
"Viande indéfinissable",
"Là-haut",
"Catapulte calibrée",
"Carte améliorée",
"Ceinture à poches",
"Piqure de calmant",
"Pulvérisateur",
"Potager",
"Conduite daération",
"Parrain très convaincant",
"Fiole de poison",
"Uppercut sauvage",
"Festival du Jeu Vidéo 2010",
"Vidéoprojecteur",
"Charognard",
"Architecte visionnaire fou",
"Vodka Marinostov",
"Masque Voodoo",
"Sorcier vaudou",
"Veille",
"Liasse de billets",
"Debout-les-morts",
"Muraille",
"Remparts avancés",
"Paladin",
"Zombie en devenir",
"Tourniquet",
"Hangars de stockage",
"Veille avec les Scouts",
"Veilleur",
"Veilleur",
"Tour de guet",
"Bombe à eau",
"Percée",
"Bonbonne deau",
"Filtre",
"Canons à eau",
"Pistolet à eau",
"Centrale hydraulique",
"Purificateur",
"Micropur effervescent",
"Ration deau",
"Aqua tourelles",
"Âme faible",
"Décharge piégée",
"Grand Catalogue Kiela",
"louest",
"Je naurais pas dû gober ça.",
"Où est mon pot dor, maudit voleur!",
"Maître du PMV",
"Aspi-rituel",
"Bête sauvage",
"Dresseur de bêtes sauvages",
"Flâneur nocturne",
"Grand Veinard en chef",
"Gagnant dans lâme !",
"Gagnant de GSP",
"Winners dont use drugs !",
"Guiness",
"Morceau de grillage",
"Bobine de fil de fer",
"Pénurie de drogue",
"Sans toit ni foie",
"Témoin de la Grande Contamination",
"Construction de Merveilles",
"Grande roue de Grostas",
"Merveilleusement futile",
"Caddie bancal",
"Déchardes de bois",
"Renforts durgence",
"Barrières",
"Atelier",
"Dégoteur de vers",
"Sacoche usée",
"Blessure - Bras",
"Blessure - Œil",
"Blessure - Pied",
"Blessure - Main",
"Blessure - Tête",
"Blessure - Jambe",
"Camion en panne",
"Ferraille",
"Poupée Vaudou XXL",
"Vous.. ne.. passerez.. PAS !",
"Ta maison est ma maison",
"Campeur de lau-delà",
"Détenteur de la Pile Sacrée",
"Favori des zombies",
"Râpe à zombies",
"Zombies éliminés",
"Zone",
"Chope De Liquide Tiédasse",
"Teckel Galeux",
"Rétroprojecteur Rétro",
"Bretzel Sableux",
"Bâton De Hurling Primitif",
"Pinte Collante",
"Pins De Collectionneur",
"Thermes de l'Or bleu",
"Grande roue de Grostas",
"Ajustement défensif",
"Gouttières crasseuses",
"Lance-grenades",
"Salle de garde",
"Meuleuse manuelle",
"Espace nature des Ermites",
"Plateforme d'observation",
"Décharge organisée",
"Animalerie",
"Porcherie",
"Bassin",
"Citrouilles ravagées",
"Sanctuaire",
"Galeries des Fouineurs",
"Repaire des Éclaireurs",
"Source Purificatrice d'Âme",
"Toilettage des Apprivoiseurs",
"Établi des Techniciens",
"Ville souterraine",
"Plan d'urbanisme",
"Mines vitaminées",
"Citrouille impressionnante",
"Boîte à pharmacie",
  "Guirlande de Corbeaux",
"Bunker abandonné",
"Hôpital abandonné",
"Hôtel abandonné"];
module.exports = {array}
