
export const array = [
"4000 zombies gaze at us",
"5th wheel of the caravan",
"A BMW M3? Too easy!",
"A caravan with no wheels???",
"A crack? What crack?",
"A letter with no address",
"A place for everything",
"A real children's game!",
"Abandoned Construction Site",
"Abandoned Park",
"Abandoned Well",
"Abbatoir",
"Abject Panic",
"Absinthe from drinking next time eh?!",
"Accursed Soothsayer",
"Ace",
"Acid Spray",
"Adjustable Spanner",
"Aesthetics Expert",
"Aggressive citizen",
"Air Strike",
"Alcohol",
"Ali Baba",
"All or Nothing",
"All the way to the end and a bit further",
"All you need is love... and Hero days",
"All-round Handyman",
"Allllllmooooooost, ah nope, damn it!",
"Alone in the Dark",
"Altar",
"Amateur Lab Rat",
"Ambulance",
"Amophilis psychotropia",
"Amped up and ready to roll",
"Anabolic Steroids",
"And on the 7th day, he did not rest!",
"Animal Dump",
"Animated Corpse",
"Anti-personnel HiFi",
"ANZAC Badge",
"Apocalyptic Garbageman",
"Apple",
"Apple Tree",
"April 1st",
"Aqua-Splash",
"Archaeologist",
"Architect",
"Architect’s Study",
"Architects Chest",
"Archivist",
"Are we there yet?",
"Armageddon",
"Armageddon Lunch Box",
"Armageddon Witness",
"Armour Plating",
"Armour Plating v2",
"Armour Plating v3",
"Arms",
"Army Outpost",
"Artful Dodger",
"Assault Rifle",
"Atomic deaths",
"Attach the testicle clamps!",
"Automatic Piston Lock",
"Automatic Sprinkler",
"Autonomous junk",
"Award for the tamer members who won the Clash of the Titans event!",
"Baby its cold outside...",
"Bag of Cement",
"Bag of Damp Grass",
"Bait",
"Bandage",
"Banishments",
"Banned Citizens Note",
"Barbed Wire",
"Barney Gumble of the world beyond",
"Battery",
"Battery Launcher 1-ITF",
"Battery Launcher Builder",
"Battlements",
"Bear Grylls",
"Bedside Lamp",
"Beer Fridge",
"Beer mug",
"Beginner Corpse",
"Belt",
"Best of The King CD",
"Betapropine 5mg",
"Bin Raker",
"Bird of bad omen",
"Black Neck Ooze",
"Blockage of construction sites",
"Blocked Road",
"Blood n Bile Spitter",
"Bloody Dressing",
"Bloody Hot Coffee",
"Blue Fire-breather",
"Bob the builder",
"Body Bouncer",
"Boiling Fog",
"Bomb Factory",
"Bonfire",
"Both Eyes Open",
"Bottle Opener",
"Bottle Opener Blank",
"Box Cutter",
"Box of Fireworks",
"Box of Games",
"Box of Matches",
"Boxes",
"Brave Prospector",
"BRDs for everyone! The people demand BRDs",
"Break Through",
"Breakages",
"Brick S**thouse",
"Bring out the gimp!",
"Britney Spears CD",
"Broken Electronic Device",
"Broken Hacksaw",
"Broken Human Bone",
"Broken Staff",
"Broken-down Tank",
"Brothers in Arms",
"Bruce Campbell",
"Bruce Lee of the trowel",
"Brutal Cannon",
"Buddha",
"Builder",
"Builder’s Merchant",
"Building Registry",
"Building Repairs",
"Bump Key",
"Bump Key Blank",
"Bunker Blueprint (rare)",
"Bunker Blueprint (uncommon)",
"Bunker Blueprint (very rare!)",
"Buried building",
"Buried Voluntarily",
"Burn him, see if his ashes turn green!",
"Burning Laser Pointer",
"Burnt Marshmallows",
"Burnt out Torch",
"Burnt School",
"Butcher",
"Cafetière",
"Camouflage Vest",
"Camp Bed",
"Camping",
"Can",
"Can Opener",
"Cannibalism",
"Cannon Mounds",
"Cantine Cook",
"Captain Hook",
"Car Door",
"Carcinogenic Oven",
"Carved Soft Pumpkin",
"Casual S+M Enthusiast",
"Catapult",
"Cave",
"Cement & Garfunkle",
"Central Cafeteria",
"Central Laboratory",
"Certified Charlatan",
"Chainsaw",
"Chainsaw Massacre",
"Chainsaws",
"Champion of the people",
"Charitable Soul",
"Che Guevara of the desert",
"Cheat Death",
"Check out my knick-knacks",
"Check out my skin sombrero!",
"Chest",
"Chicken",
"Chief DIY",
"Chinese Noodles",
"Chiseler",
"Chocolate Cross",
"Chocolate log",
"Christmas",
"Christmas candy",
"Christmas Present",
"Chuck Figurine",
"Chuck Norris",
"Cinema",
"Citizen",
"Citizen trafficker",
"Citizens",
"Citizens Home",
"Citizens Tent",
"Citizens Welcome Pack",
"Clairvoyance",
"Clash CEO",
"Clash Colossus",
"Clash Team",
"Clash Titan",
"Claymore Mine",
"Clean",
"Cleptomaniac",
"Close ranks and hold on!",
"closed",
"Clubs",
"Coffin Catapult",
"Collapsed Mineshaft",
"Collapsed Quarry",
"Comic book fan",
"Commis Chef",
"Community Awards",
"Community Companion",
"Community Extremist",
"Community Involvement",
"Community Spirit",
"Community Über-Activist",
"Compact detonator",
"Compass Included",
"Complaints",
"Concrete Reinforcement",
"Construction Blueprint (common)",
"Construction Blueprint (rare)",
"Construction Blueprint (uncommon)",
"Construction Blueprint (very rare!)",
"Construction Kit",
"Construction Site Shelter",
"Construction Sites",
"Constructions",
"Convex Lens",
"Copper Pipe",
"Coquette",
"Corner Chemist",
"Corpse Cop",
"Corpse Crusher",
"Corrosive Liquid",
"Corvidæ specialist",
"Cosmetics Lab",
"Cosmic Sponsor",
"Covert Concierge",
"Craftsman",
"Crate Lid",
"Cremato-Cue",
"Crow elf",
"Crow garland",
"Crow Statue",
"Crows buddy",
"Crows Nest",
"Crucifixion",
"Crushed Battery",
"Curious reader",
"Cursed Cuddly Toy",
"Cursed HiFi",
"Cyanide",
"Dachshund",
"Dances with Hordes",
"Dances with zombies",
"Danny Ocean",
"Daredevil Camper",
"Dark Woods",
"Day",
"Daylight Lantern",
"Dead in your bed",
"Deadbolt Dick",
"Deaths by Dehydration",
"Deaths by Infection",
"Deaths from withdrawal",
"Decon Shower",
"Decorated Veteran",
"Decoration",
"Defence Dump",
"Defender",
"Defensive Focus",
"Defensive Thinktank",
"Dehydrated fellow",
"Dehydrated!",
"Demented Master Builder",
"Demi Chef de Partie",
"Depleted zone",
"Derelict Villa",
"Descendant of the Atlanteans",
"Desert Historian",
"Desert Orphant",
"Desert Rat",
"Desert Shackleton",
"Desert showman!",
"Desert speculator",
"Deserted Freight Yard",
"Destroyed Pharmacy",
"Devastator (empty)",
"Devastator (incomplete)",
"Devastator (loaded)",
"Dialysis",
"Diamonds",
"Dice",
"Dictator",
"Dilapidated Building",
"Dirty Uniform",
"Dismantled Mower",
"Distant Discoveries",
"Distant Region",
"Disused Car Park",
"Disused Silos",
"Divine Mystic",
"Divine Soul",
"Divining Rocket",
"Divining Rods",
"Do you feel lucky, punk?",
"Dodgy Homemade Dish",
"Does it smoke? It is from me.",
"Dog food doesn't taste so bad",
"Doggy Bag",
"Don't call me Junior",
"Don't cross the streams",
"Don't wait up...",
"Don't you have better things to do?",
"Doormat",
"Dora the Explorer",
"Dr Deaths Dietician",
"Dried Chewing Gum",
"Dried Marshmallows",
"Drilling Rig",
"Drink",
"Drug Tests",
"Drugged",
"Drugged Labradoodle",
"Drugs",
"Drunk",
"Duct Tape",
"Dukes Villa",
"Dump",
"Dump Upgrade",
"Dumpster Diver",
"Dune Ranger",
"Dusty Book",
"Earplugs",
"East",
"Easter",
"Easter Egg",
"Eden Project",
"Edit Piaf",
"Egg",
"Ektorp-Gluten Chair",
"Electric Whisk",
"Electronic component",
"Emancipation of the Shunned",
"Emergency Supplies",
"Empty Oil Can",
"Empty Vending Machine",
"EMS System",
"Encyclopedia",
"Engine",
"Enlightened Builder",
"Enlightened Preacher",
"Envelope",
"Equal to Chuck Norris",
"Equipped Trench",
"Ergot Fungus",
"Ergot Homebrew",
"Escort",
"Eternally second",
"Everything for my mouth",
"Evolutive Wall",
"Excavations",
"Excessive water consumption",
"Exhausted",
"Exhausted",
"Expedition Expert",
"Expert Expeditions",
"Exploding Grapefruit",
"Exploding Water Bomb",
"Exterminator",
"Extra large love",
"Extraordinary citizen",
"Extrawall",
"Extreme BBQ Chef",
"Extreme Explorer",
"Extreme Projects",
"Eye",
"Eye of the desert",
"Factory",
"Fairground Stall",
"False Bottom",
"False Town",
"Family Tomb",
"Fast Food Restaurant",
"Fat Cat",
"Fat Serpent",
"Father Christmas is a little rascal",
"Father Christmas is a little sh*t",
"Faucet",
"Fearfulness Wheel",
"Fearless adventurer",
"Fed",
"Fence",
"Fertilizer",
"Festering Flesh",
"Fights of despair",
"Fill",
"Firework Foray",
"Firework Launch Tube",
"Fitter",
"FJV08 cannon fodder",
"Flash Grenade",
"Flash Powder",
"Flatpacked Furniture",
"Flee",
"Fleet-footed Coyote",
"Fleshroom Puree",
"Fleshrooms",
"Food Dump",
"Food Parcel",
"Foot",
"Fortifications",
"Foul-smelling Red Hat",
"Foul-smelling Vintage Suit",
"Foundations",
"Founder of Timewasting",
"Fraser Ds Kebab-ish",
"Frat House",
"Free citizen!",
"Free Dump",
"Fresh flesh peddler",
"Friends? Who needs em!",
"Fruit Loop Engineer",
"Full Jerrycan",
"Full of protein.",
"Fund re-allocation specialist",
"Furious Kitten",
"Gallows",
"Garbage Dump",
"Garden Shed",
"Gas Gun",
"Gazette",
"Geeks tracker",
"Generosity",
"Gentleman Robber",
"Get some Duct Tape in there.",
"Ghoul",
"Ghoul Vaccine",
"Giant BRD",
"Giant Rat",
"Giant Sandcastle",
"Gift Parcel",
"Gimme a drink or the dog gets it!",
"Glory",
"Glory to the Crow!",
"Gnawed Corpse",
"Go ahead, make my day!",
"Golden Child",
"Golden Showerer",
"Gollum of the Labyrinths",
"Good Guy",
"Good taste personified",
"Grand Key Master",
"Grapeboom",
"Grater",
"Great Architect",
"Great Independent Hermit",
"Great Mason",
"Great Moat",
"Great Pit",
"Great, benevolent, all-powerful creator",
"Green Beer Bottle",
"Green Imp Suit",
"Grisly Bomb",
"Groundsheet",
"Guard Dog",
"Guard of the seals",
"Guard Tower",
"Guardian",
"Guardian - Winner of SoH",
"Guerilla Traps",
"Guide to the World Beyond",
"Guinea Pig",
"Guns n Zombies Armoury",
"H2Operative",
"Hacksaw",
"Half-eaten Chicken Wings",
"Halloween",
"Hammam",
"Hand",
"Handful of Bullets",
"Handful of nuts and bolts",
"Handful of Sweets",
"Handyman's Toolbelt",
"Hanging",
"Happiness of magnitude 8",
"Happy as Larry",
"Happy hampster",
"Harbinger of the Plague",
"Hardcore my love!",
"Hardcore? Candy from babies...",
"Hardened Hermit",
"Hastily-built Desk",
"Have you got a light?",
"He was a liver...",
"Head",
"Head Shoveler",
"Healed",
"Healthy Body",
"Hearts",
"Hell is a walk in the park.",
"Hell? I eat a little bit of it for breakfast",
"Hello... Is there anybody out there?",
"Henhouse",
"Hero",
"Hero board",
"Heroic Actions",
"Heroic Return",
"Hey hey, wanna see my... Battery?",
"High Priestess of the Sun Temple",
"Highly experienced player",
"Hold your positions!",
"Holocaust cannibals",
"Holy F***ing Iceberg",
"Holy Raincloud",
"Home",
"Home Depot",
"Home Depot Regular",
"Home Improvements",
"Home Laboratory",
"Homemaker",
"Homosapien / Labradoodle cross",
"Hooked!",
"Horizon traveller",
"Hospital Blueprint (rare)",
"Hospital Blueprint (uncommon)",
"Hospital Blueprint (very rare!)",
"Hot Air Balloon",
"Hotel Blueprint (rare)",
"Hotel Blueprint (uncommon)",
"Hotel Blueprint (very rare!)",
"House",
"Hovel",
"How about some Chubb-ly?",
"Huge Snake (Ophiophagus trouser)",
"Human Flesh",
"Hundesteaks: Anyone for a fat-cat-kebab?",
"Hungover",
"Hungry Jackal",
"Hurling stick",
"Hydratone 100mg",
"Hydraulic Network",
"Hydraulics Engineer",
"I ain't afraid of no ghost",
"I am a beast!",
"I am a god! I will live forever!",
"I am legend.",
"I am watching you...",
"I can recite pi to infinity!",
"I can see the zeds from here!",
"I do not need anyone",
"I don't miss anything.",
"I eat nails and sh*t bullets!",
"I have a plan",
"I know I have a grain",
"I see dead people - everywhere!",
"I see dead people 0_0",
"I taste all my products",
"I think you are underestimating the sneakiness...",
"I walk alone.",
"I\'m a believer",
"I\'ve been round the world... Twice!",
"I\'ve even dug through a public toilet!",
"I\'ve got a sore tummy...",
"I\'ve got everything you need.",
"If its under 55 proof its water!",
"If were meant to eat vegetables, why are animals so tasty?",
"If you want to live... Follow me!",
"Ill let myself in...",
"Illegible Notebook",
"Illuminated Guide",
"Im a believer",
"Im Batman",
"Im dizzy",
"Im working on the Sagrada",
"Immunised",
"Impersonal Exploding Doormat",
"In at the deep end!",
"In with the bricks",
"Incomplete Cafetière",
"Incomplete Chainsaw",
"Incomplete Deck of Cards",
"Incredible determination",
"Indian Burial Ground",
"Indiana Jones",
"Indiana Jones and the ruins of the World Beyond",
"Infected",
"Infected with a poison",
"Infirmary",
"Injuries",
"Inner Wall",
"Insatiable Citizen",
"Inspiration for the people",
"Instruction Manual",
"Insults or behaviour",
"Insurmountable citizen",
"Interior designer",
"Internet Explorer",
"Intestine Melon",
"Irish pockets are bulging!",
"Iron Chest",
"Is it a bird? Is it a plane? No, its the super battery launcher!",
"It is death that should be afraid of me!",
"It was smaller on the catalog",
"Its better when they scream.",
"Its just too easy.",
"Jack",
"Jack Pott",
"Järpen Table",
"Jean Claude Van Damned",
"Jerrycan Gun",
"Just one finger!",
"Just Say No!",
"Kalashni-Splash",
"Keen Sceptic",
"Keeper of pleasures",
"Keeps too many items for themselves",
"Key hee hee!",
"King",
"Kitchen",
"Kwik-fix",
"Lab Rat",
"Label",
"Labourer",
"Labyrinth",
"Labyrinth Master PhD",
"Large Chested",
"Large Curtain",
"Large Gift Parcel",
"Large Metal Chest",
"Laser Diode",
"Last Bastion",
"Last Boy Scout",
"Last line of defence",
"Last Man Standing",
"Last Man Standing - Hardcore!",
"Last-Minute Lock",
"Lawnmower",
"Leak Plugger",
"Learned Camper",
"Leg",
"Legend of Labradoodle",
"Legend of the World Beyond",
"Legendary tamer",
"Legendary Towns!",
"Librarian",
"Light in the night",
"Lighthouse",
"Listen to my voice",
"Lit Pumpkin",
"Little Book of Calm",
"Local Butcher",
"Local Dealer",
"Lock",
"Lonely...Im so lonely",
"Long-sighted",
"Looted Supermarket",
"Lost Soul",
"Lost World Messiah",
"Love guru",
"low",
"LSD",
"Lucifers dance partner",
"Luck",
"Lucky 7",
"Lucky Find",
"Lunches like Lecter",
"MacGyver of the World beyond",
"Machete",
"Macs Atomic Cafe",
"Magnetic Key",
"Magnetic Key Blank",
"Make it rain!",
"Makeshift Barricade",
"Makeshift Guitar",
"Making things happen!",
"Mamas Finest",
"Man vs World Beyond",
"Manbag",
"Manipulator",
"Map",
"Marco Pierre Die2Nite",
"Marquee Master",
"Martine at the beach",
"Masochism",
"Master Architect",
"Master Builder",
"Master Chef",
"Master Guardian",
"Master of futility",
"Master Rootfinder",
"Master Scavenger",
"Master Thief",
"Masterpieces in Peril",
"Mattress",
"Mayor",
"Me vs. the Horde!",
"Meat Locker",
"Meat Muncher",
"Meaty Bone",
"Mechanical Pump",
"Mechanism",
"Member of the Red Cross",
"Memory of civilization",
"Messages",
"Metal Chest",
"Metal Dump",
"Metal Patches",
"Metal Support",
"Mines",
"Mini HI-Fi",
"Mini-market",
"Miniature Armory",
"Minimal participation",
"Ministry of Slavery",
"Mist Spray",
"Mobile Phone",
"Modern obelisk!",
"Money for Nothing",
"Moonlight Stroller",
"More Storage",
"Motel 666 Dusk",
"Motivated Hordian festival-goer",
"Motorway Services",
"Mouldy Ham Sandwich",
"Mouldy Neapolitan",
"Mount Killaman-Jaro",
"Mr Writer",
"Mutilator",
"My name is nobody",
"Mystic Points",
"Mystic Potion",
"Mystical transformation",
"Myth in the making",
"Neil Armstrong of the World Beyond",
"Ness-Quick Weedkiller",
"Never goes outside",
"Never touch the stuff, me.",
"Never without my bucket",
"Night in the desert",
"No Holes Barred",
"Noble Heart",
"Noble Soul",
"Nonsense builder",
"North",
"North-East",
"North-West",
"Not even afraid!",
"Not without my dog!",
"Novelty Torch",
"Nuclear Bunker",
"O Soul-e Mio",
"Objects",
"Old Aerodrome",
"Old Bicycle Hire Shop",
"Old Door",
"Old Field Hospital",
"Old Hydraulic Pump",
"Old Police Station",
"Old Saint Nick is a little **it",
"Old Washing Machine",
"Old-school traps",
"Omniscience",
"Once-inhabited Cave",
"One Eye Open",
"One for the books",
"One town to rule them all!",
"Open Can",
"Open-chakra",
"opened",
"Opened packet of Cigarettes",
"Out-of-Date Biscuits",
"Packet of Soft Crisps",
"Padlock and Chain",
"Palace",
"Pandemonium",
"Paracetoid 7g",
"Paranoid and Proud",
"Parcel",
"Partially Putrified",
"Participating Town",
"Patch-up Specialist",
"Patchwork Beam",
"Pathetic Penknife",
"PC Base Unit",
"People’s Court",
"Permanent member of the Mickey Club",
"Persian Rug",
"Pharmaceutical Products",
"Phil Collins CD",
"Phoenix of the desert",
"Photo Album",
"PI-KEYA Furniture",
"Pigeon from the outer world.",
"Pilager of the liquor store.",
"Pillager",
"Pillages",
"Pillar of the community",
"Pine Fresh Smoke Bomb",
"Pits",
"Plane Crash Site",
"Plastic Bag",
"Plastic Bag and Semtex",
"Plate Gun",
"Platinum Showerer",
"Plunderer",
"Plywood",
"Pocket Companion",
"Pocket Vibrator",
"Portal Lock",
"Post Office",
"Post-mortem Pickpocket",
"Potion Preparer",
"Pound of Flesh",
"Powerful Soul",
"Pre-war camera",
"Predictor",
"Prepare the gallows - were hanging Santa!",
"Pretzel",
"Preventative Medicine",
"Private Town",
"Pro Camper",
"Pro-Watchman",
"Prodigy",
"Product Tester",
"Product Tester!",
"Profession",
"Psychadelic Spiritual Counsel",
"Psychic for rent",
"Public lights",
"Pukka Chef",
"Pump",
"Purified Stagnant Water",
"PUTA Mark II Calibrator",
"Pyramid shmyramid",
"Quality Log",
"Queen",
"Radiant citizen",
"Radio Cassette Player",
"RadioactiveMan",
"Radius Mark II",
"Radius Radar Beacon",
"Railgun",
"Rambos ancestor",
"Rampart Chief",
"Rancid Jaffa Cakes",
"Ranked Towns",
"Rat Roaster",
"Reactor",
"Recycle",
"Refresh",
"Refreshed",
"Regular at the Pandemonium Sauna",
"Regularly A-mazed!",
"Reincarnator",
"Reinforced Gates",
"Reinforcements",
"Removals",
"Renovator to the stars",
"Repair Kit",
"Repairs",
"Rescue",
"Resourcefulness",
"Revolver",
"Riot Shield",
"Ripped Red Trousers",
"Rock Cannon",
"Rock n Roll HiFi",
"Rocking Chair",
"Roleplayer",
"Rookie Mode",
"Rotting Log",
"Rubbish Heap",
"Rucksack",
"Rudimentary Alarm",
"Ruin",
"Ruin Explorations",
"Ruin Restorer",
"Rusty Chain",
"Rusty Ryan",
"Sabotage of expeditions",
"Safe",
"Safehouse",
"Samaritan",
"Sand Ball",
"Sand balls!",
"Sand Phantom",
"Sand Shifter",
"Sandcastle",
"Sandman",
"Sandy Maverick",
"Saniflow Macerator",
"Santa Claus is a thieving b*****d",
"Santa is a crook",
"Santa's Reindeer",
"Saviour of Citizenkind",
"Sawdust Steak",
"Scanner",
"Scarecrows",
"Scavenger",
"Scavenger - Winner of SoH",
"Schrödinger\'s Box",
"Scottish Smiths Superstore",
"Scourge of the animal kingdom...",
"Scout",
"Scrap Metal",
"Screaming Alarm Clock",
"Screaming Saws",
"Screwdriver",
"Scroll",
"Sealed Architects Chest",
"Search the refuse",
"Searchtower",
"Second Breakfast",
"Second Lease of Life",
"Second wind",
"Second-hand Red Coat",
"Sect Member",
"Seeker",
"Selfish play",
"Semtex",
"Serrated Knife",
"Sesame, shift your A...",
"Shack",
"Shadow Master",
"Shady Bar",
"Shaman",
"Sheet Metal",
"Sheet Metal (parts)",
"Sheet of Plywood",
"Shim Surgeon",
"Shock of Heroes",
"Shooting Gallery",
"Shopping Trolley",
"Shower",
"Shrewd Citizens Stash",
"Shunned",
"Siesta Time",
"Silver Showerer",
"Site Manager",
"Slip n Slide",
"Sluice",
"Small Café",
"Small Cemetary",
"Small Fence",
"Small House",
"Small Spade",
"Small Town",
"Small Trebuchet",
"Smoke? What smoke?",
"Snake oil salesman",
"Sneaky Voyager",
"So I guess were not waiting for Bob?",
"Social Animal",
"Social Support",
"Soft Pumpkin",
"Solicitor of the World Beyond",
"Solid Wooden Board",
"Soul Calipers",
"Soul Collector",
"Soul Mason",
"Soul of the professional",
"Soul Purificator",
"Soul Recycler",
"Soul salesman",
"Soul-dier",
"South",
"South-East",
"South-West",
"Souvenir Collector",
"Spades",
"Spanners and Bump keys",
"Spicy Chinese Noodles",
"Spiked Pit",
"Spiked Wall",
"Spikes",
"Spirit Mirage",
"Spiritual Guide",
"Sprinkler",
"Spy Flare",
"St. Patrick",
"Stack of Papers",
"Staff",
"Stagnant Water Can",
"Stake Launcher",
"Stale Tart",
"Standing ovation",
"Statue of the Crow",
"Sticky Pastry Ball",
"Stiff Shifter",
"Stinking Pig",
"Storyteller",
"Strange Circular Device",
"Strong Spices",
"Stronghold",
"Style is eternal...",
"Suicide Sleeper",
"Super Soaker",
"Super-Fuzz Powder",
"Superhero in training",
"Survival Book",
"Survivalist",
"Survivalist - Winner of SoH",
"Survivor of Hell!",
"Suspicious looking plum juice",
"Suspicious-looking Vegetable",
"Swedish Workshop",
"Sweet Revenge",
"Swiss Army Knife",
"Sword of Bokor",
"Talks to the animals",
"Tamer",
"Taser",
"Tasty Dishes",
"Tasty Homemade Dish",
"Tasty-looking Steak",
"Taught Sam Fisher everything he knows!",
"Tavern robber",
"Tea Leaf",
"Technician",
"TechnicoMecanoMegalo",
"Teddy Bear",
"Telescope",
"Tent",
"Tenzing Norgay",
"Terraforming Specialist",
"Terrorised",
"That\'ll last another 10 years!",
"The Bank",
"The batterinator.",
"The Big Rebuild",
"The BRD Screwdriver Combo",
"The Fixer",
"The Great Wall of what?",
"The guard may perish, but he never gives up!",
"The Hitman",
"The human ant",
"The Invisible Man",
"The Last Survivor",
"The Mayor-Mobile",
"The name\'s Nate Fortu",
"The Peacemaker",
"The Rock!",
"The second last of the Mohicans",
"The Shattered Illusions Bar",
"The sky is falling!!!",
"The Sneak",
"The time for cathedrals has come",
"The truth is elsewhere",
"The Well",
"Theft of multiple objects",
"Thefts",
"There ain't nothing I cant take this chainsaw to...",
"Theres a battery with your name on it...",
"They named a constellation after me",
"Thick Solution",
"Third Wall",
"Thirsty",
"This leprechaun is unstoppable.",
"Thousand I-lived",
"Three rivers dam... Thats adorable.",
"Three-legged Labradoodle",
"Tin-soul town",
"Tired Labradoodle",
"Tireless tumbler tickler",
"To infinity and beyond!",
"Tombstone Toppler",
"Tool Bag",
"Toolbox",
"Torch",
"Tortured Soul",
"Tower",
"Town",
"Town Library",
"Town Planner",
"Town plasterer",
"Town Uniform",
"Town Upgrades",
"Toxin",
"Traveller's Corpse",
"Treachery",
"Trestle",
"Trusted Neighbour",
"Tunnel Visionary",
"Twinoid 500mg",
"Twinoid is taboo",
"Twisted Plank",
"Type 4 Encounter",
"Uber-Aware",
"Überwall",
"Ultimate Fighter",
"Ultimate Hordian Explorer",
"Ultra Scavenger",
"Ultra-Rucksack",
"Undecided",
"Under Chef",
"Unlabelled Drug",
"Unrecognisable Remains",
"Unshakeable Camper",
"Unshaped Concrete Blocks",
"Unspecified Meat",
"Up there",
"Upgraded Catapult",
"Upgraded Map",
"Utility Belt",
"Valium Shot",
"Vaporiser",
"Vegetable Plot",
"Ventilation System",
"Very convincing sponsor",
"Vial of Poison",
"Vicious Uppercut",
"Video Game Festival 2010",
"Video Projector",
"Viking",
"Visionary Architect",
"Vodka Marinostov",
"Voodoo Mask",
"Voodoo Sorceror",
"W-Men",
"Wad of Cash",
"Wake The Dead",
"Wall Upgrade v1",
"Wall Upgrade v2",
"Wandering Knight",
"Wannabe Zombie...",
"War Mill",
"Warehouse",
"Watches with Scouts",
"Watchman",
"Watchmen",
"Watchtower",
"Water Bomb",
"Water Catcher",
"Water Cooler Bottle",
"Water Filter",
"Water Guns",
"Water Pistol",
"Water Processing Plant",
"Water Purifier",
"Water Purifying Tablets",
"Water Ration",
"Water Turrets",
"Weak Soul",
"Weapons Dump",
"Welcome to the palace.",
"West",
"What do you mean these aint skittles",
"Wheres my pot of gold, thieving pikey!",
"Whip me harder!",
"Who you gonna call?",
"Wild Beast",
"Wild Beast Tamer",
"Wild-eyed Wanderer",
"Windfall Catcher",
"Winner at heart!",
"Winner of CYP",
"Winners dont use drugs!",
"Winness",
"Wire Mesh",
"Wire Reel",
"Withdrawal",
"Without a roof or a tooth.",
"Witness to the Great Contamination",
"Wonder Constructions",
"Wonder Wheel",
"Wonderfully futile",
"Wonky Shopping Trolley",
"Wood Dump",
"Wood Plating",
"Wooden Fencing",
"Workshop",
"Wormfinder General",
"Worn Leather Bag",
"Wounded - Arm",
"Wounded - Eye",
"Wounded - Foot",
"Wounded - Hand",
"Wounded - Head",
"Wounded - Leg",
"Wrecked Transporter",
"Wrought Iron",
"XXL Voodoo Doll",
"You... shall... not...PASS!",
"Your home is my home",
"Zen Camper",
"Zen-ergizer",
"Zombie favourite",
"Zombie Grater",
"Zombies eliminated",
"Zone"];
