 let array = [
"4000 zombies nos miran",
"Quinta rueda de la caravana",
"¿Dónde está Larchi?",
"¿¿¿Una caravana sin ruedas???",
"¿Una grieta? ¿Qué grieta?",
"Una carta",
"Bolsillos inteligentes",
"¡Un verdadero juego de niños!",
"Sitio de construcción abandonado",
"Parque abandonado",
"Pozo abandonado",
"Matadero",
"Ataque de pánico",
"Absenta de beber la próxima vez, ¿eh?",
"Charlatán Amateur",
"As",
"Pulverizador de ácido",
"Llave inglesa",
"Maestro de la estética",
"¡Habitante agresivo!",
"Ataque aéreo",
"Alcoholes",
"Ratero",
"Todo o nada",
"Todo el camino hasta el final y un poco más lejos",
"Mesías",
"Reparador aficionado",
"Casi!!!, ah no, ¡maldita sea!",
"Carpa diem",
"Altar",
"Laboratorista amateur",
"Ambulancia",
"Medium profesional",
"Amplificada y lista para rodar",
"Esteroides anabólicos",
"¡Y al séptimo día, no descansó!",
"Vertedero de animales",
"Cadáver animado",
"Equipo Hi-Fi defensivo",
"Placa de Sheriff",
"Repelente de Macchabees",
"Manzana",
"Manzano",
"1ro de Abril",
"Rifle de agua",
"Fuerzudo del desierto",
"Arquitecto",
"Estudio de arquitectos",
"Maletín de arquitecto",
"Maestro Rolista",
"¿Ya llegamos?",
"Armagedón",
"Lonchera",
"Testigo de Armagedón",
"Tabique de madera",
"Tabique de metal",
"Tabique grueso",
"Brazo",
"Puesto militar",
"Bandido",
"Fusil de asalto",
"Muerte por radioactividad",
"Aprietame las esposas",
"Cierre automático",
"Regaderas automáticas",
"Investigador ingenioso",
"Distinción entregada a los miembros del pueblo domador que ganó el Choque de Héroes.",
"Tengo frio aquí...",
"Saco de cemento",
"Costal de hierba fresca",
"Cebo",
"Vendaje rudimentario",
"Destierros",
"Nota de un habitante desterrado",
"Alambre de púas",
"Barney Gumble del Ultramundo",
"Pila",
"Lanzapilas 1-PDTG",
"Super lanzapilas",
"Almenas",
"Sin techo ni dientes",
"Lámpara de mesa apagada",
"Frigorífico",
"Jarra de cerveza",
"Cadáver de principiante",
"Correa",
"Hits de Elvis",
"Betapropín 5mg",
"Rastrillador del vertedero",
"Ave de mal augurio",
"Moco de cuello negro",
"Bloquea las construcciones",
"Pista bloqueada",
"Escupidor de sangre y bilis",
"Tirita ensangrentada",
"Café caliente",
"Pescador de Almas",
"Ramsés del siglo XXI",
"Lanzador de cadáveres",
"Vaporizador pro",
"Polvorín",
"Fogata",
"Dos ojos abiertos",
"Abrebotellas",
"Molde para abrebotellas",
"Cutter",
"Caja de fuegos artificiales",
"Caja de juegos",
"Caja de cerillas",
"Cajas de cartón",
"Aventurero Temerario",
"¡Gloria a la COSA!",
"Pasaje en vigor",
"Torpezas",
"Erudito",
"Quiero ser un objeto",
"CD de Britney Spears",
"Aparato electrónico descompuesto",
"Sierra de metal en mal estado",
"Hueso humano",
"Palo roto",
"Tanque averiado",
"Camaradería",
"Bruce Campbell",
"El Bruce Lee de la Espatula",
"Cañón brutal",
"El Inmortal",
"Urbanista",
"Despacho de vivienda",
"Registro de obras",
"Reparación de construcciones",
"Llave de percusión",
"Molde para llave de percusión",
"Plano de construcción de búnker (raro)",
"Plano de construcción de búnker (inusual)",
"Plano de construcción de búnker (¡muy raro!)",
"Sector inexplotable",
"Brújula andante",
"¡Quémalo, mira si sus cenizas se vuelven verdes!",
"Puntero láser potente",
"Malvaviscos quemados",
"Antorcha consumida",
"Escuela quemada",
"Carnicería",
"Cafetera",
"Camuflaje",
"Camastro",
"Acampada",
"Lata de conservas",
"Abrelatas",
"Canibalismo",
"Montículos",
"Ayudante de cocina",
"Terror de las puertas",
"Puerta de coche",
"Horno cancerígeno",
"Calabaza suave tallada",
"Adepto del SM",
"Catapulta",
"Caverna",
"Cemento y Garfunkle",
"Cafetería central",
"Laboratorio central",
"Aborigen curioso",
"Sierra eléctrica",
"Masacre de la motosierra",
"Sierras elécticas",
"Héroe popular",
"Alma caritativa",
"Che Guevara del Ultramundo",
"Vencer a la muerte",
"Jefe Excavador",
"Creador de la muerte",
"Baúl",
"Gallina",
"Jefe de Manualidades",
"Tallarines chinos",
"Pillo",
"Cruz de chocolate",
"Tronco de Navidad",
"Navidad",
"Dulce de Navidad",
"Caja sorpresa",
"Muñequito de Chuck",
"Masacrador",
"Cine",
"Habitante",
"Traficante de habitantes",
"Habitantes",
"Casa de un habitante",
"Tienda de un habitante",
"Objetos de un habitante",
"Clarividencia",
"Director ejecutivo de Clash",
"Héroe de Leyenda",
"Organización de Choque",
"Titán de choque",
"Mina antipersonal",
"Limpio",
"Saqueador",
"¡Cierra filas y aguanta!",
"cerrado",
"Tréboles",
"Lanza Muertos",
"Mina colapsada",
"Cantera derrumbada",
"Fan de X-Men",
"Cocinerillo",
"Reconocimiento de la Comunidad",
"Compañero de comunidad",
"Extremista comunitario",
"Protección civil",
"Espíritu de la comunidad",
"Hiperactivista comunitario",
"Detonador compacto",
"Ruina Man",
"Denuncias",
"Capa de hormigón",
"Plano de construcción (común)",
"Plano de construcción (raro)",
"Plano de construcción (inusual)",
"Plano de construcción (¡muy raro!)",
"Caja de materiales",
"Refugio en construcción",
"Construcciones",
"Construcciones",
"Lente convexa",
"Tubo de cobre",
"Detallista",
"Químico de barrio",
"Basurero",
"Exterminador",
"Producto corrosivo",
"Especialista en córvidos",
"Laboratorio de cosméticos",
"Lider cósmico",
"Apertura de puertas",
"Artesano",
"Pedazo de caja",
"Cremato bar",
"Cuervo navideño",
"Guirnalda de cuervo",
"Estatua del cuervo",
"Amigo de los cuervos",
"Torre de exploración",
"Crucifixión",
"Pila molida",
"Lector curioso",
"Osito cariñosito maldito",
"Equipo de música maldito",
"Cianuro",
"Perro salchicha",
"Indestructible",
"Carnada para zombies",
"Chorizo temible",
"Campista temerario",
"Bosque oscuro",
"Día",
"Linterna de luz diurna",
"¡Si me muero, mejor que sea cómodamente!",
"Ábrete Sésamo",
"Muertes por deshidratación",
"Muertes por infección",
"Muertes por abstinencia",
"Cortina de agua",
"Ilustre veterano",
"Decoración",
"Vertedero de defensas",
"Defensor",
"Defensas Max",
"Soporte de defensas",
"Colega de la deshidratacion",
"¡Deshidratado!",
"Maestro constructor demente",
"Cordon bleu del barrio",
"Zona agotada",
"Pueblo fantasma",
"Descendiente de los Atlantes",
"Historiador del desierto",
"Huérfano del desierto",
"Rata del desierto",
"Cristobal Colón",
"Empresario del Ultramundo!",
"Especulador del Ultramundo",
"Plataforma ferroviaria",
"Farmatodito destruido",
"Devastador (vacío)",
"Devastador incompleto",
"Devastador (cargado)",
"Diálisis",
"Diamantes",
"Dados",
"Dictador",
"Edificio deteriorado",
"Uniforme de habitante sucio",
"Cortacésped incompleto",
"Exploraciones avanzadas",
"Leyenda",
"Carrocerías de autos",
"Silos abandonados",
"Reciclador de almas",
"Alma Divina",
"Lanza-cohetes",
"Detector de agua",
"Maestro del Azar",
"Plato casero extraño",
"¿Fumas? Este va por mi cuenta",
"La comida para perros no sabe tan mal",
"Doggy-bag",
"No me llames junior",
"No cruces los arroyos",
"Todo terreno",
"¿No tienes algo mejor que hacer?",
"Felpudo",
"Explorador Impetuoso",
"Fan de Hannibal",
"Chicles secos",
"Malvaviscos secos",
"Taladro",
"Beber",
"Experimentaciones",
"Drogado",
"Bichón maltés eufórico",
"Estimulantes",
"Ebrio",
"Adhesivo",
"Mansión de Duke",
"Vert.",
"Vertedero mejorado",
"Recolector de basura",
"Amante del riesgo",
"Libro empolvado",
"Tapones de oído",
"Este",
"Pascua",
"Huevo de Pascua",
"Proyecto Edén",
"Edit Piaf",
"Huevo",
"Silla Ektörp-Gluten",
"Batidora eléctrica",
"Componente electrónico",
"Desterrado emancipado",
"Defensas de urgencia",
"Bidón de aceite vacío",
"Cajero vacío",
"ElectroGym",
"Una enciclopedia",
"Motor",
"Obrero Optimista",
"Predicador iluminado",
"Un sobre",
"Igual a Chuck Norris",
"Trincheras militares",
"Claviceps Purpurea",
"Cidra claviceps artesanal",
"Escolta",
"Eterno segundo",
"Todo para mi boca",
"Muralla evolutiva",
"Desmonte",
"Consume demasiada agua",
"Cansado",
"Cansado",
"Explorador impetuosísimo",
"Exploraciones muy lejanas",
"Pomelo explosivo",
"Bolsa de agua explosiva",
"Mutilador",
"Amor extra grande",
"Habitante fuera de serie",
"Muro extra",
"Cocina exótica",
"Caminante del Horizonte",
"Proyectos delirantes",
"Ojo",
"Ojo del Ultramundo",
"Fábrica",
"Stand de feria de atracciones",
"Fondo Falso",
"Pueblo falso",
"Cripta familiar",
"Restaurante «Burger Twin»",
"Gato bonito",
"Serpiente agonizante",
"Santa es un pillo",
"Maldito Papá Noel",
"Grifería",
"Gran Noria de Znarf",
"Viajero sin miedo",
"Sin hambre",
"Valla",
"Fertilizante",
"Pellejo humano",
"Combates mortales",
"Llenar",
"Fuegos artificiales",
"Tubo de lanzamiento de fuegos artificiales",
"Manitas hábiles",
"Carne de cañón FJV08",
"Bomba de carnaval",
"Pólvora brillante",
"Mueble para armar",
"Huir",
"Canalla",
"Puré de hongos carroñeros",
"Hongos carroñeros",
"Vertedero de comida",
"Caja de alimentos",
"Pie",
"Fortificaciones",
"Gorro rojo maloliente",
"Traje de Papá Noel",
"Cimientos",
"Obrero Iluminado",
"Sándwiches «San Guchito»",
"Fiesta en casa",
"¡Habitante libre!",
"Vertedero gratuito",
"Comerciante de carne fresca",
"Omnívoro",
"Ingeniero de Fruit Loop",
"Cantimplora llena",
"Lleno de proteínas.",
"Especialista en reasignación de fondos",
"Gatito furioso",
"Horca",
"Vertedero público",
"Cabaña de jardín",
"Cañón aspirina",
"Boletín",
"Rastreador friki",
"Generosidad",
"Abridor de puertas",
"Ponga cinta adhesiva allí.",
"¡Mutante!",
"Vacuna para mutante",
"Gran COSA",
"Rata gigante",
"Gran Castillo de Arena",
"Paquete de regalo",
"¡Dame un trago o el perro sufrira las consecuencias!",
"Fama",
"¡Gloria al cuervo!",
"Cadáver carcomido",
"Mordedor de muertos",
"Gurú Rico",
"¿Un chorrito más señor?",
"Tomb Raider",
"Buen chico",
"Habitante con buen gusto",
"Gran maestro de llaves",
"Pomelo explosivo",
"Muro de faquir",
"Constructor visionario",
"Gran Eremita independiente",
"Arquitecto estrambótico",
"Gran charco",
"Zanja periférica",
"Albañil Dominguero",
"Vodka Rosquetoff",
"Traje de duendecillo",
"Bomba macabra",
"Tela de carpa",
"Perro guardián",
"Guardia de las focas",
"Torre de guardia",
"Guardián",
"Campeón de Choque de héroes",
"Trampas de guerrilla",
"Guía del Ultramundo",
"Conejillo de Indias",
"Armería GunsnZombies",
"Especialista con armas de agua",
"Sierra de metal",
"Alitas de pollo mordidas",
"Halloween",
"Hammam",
"Mano",
"Puñado de balas",
"Puñado de tornillos y tuercas",
"Puñado de caramelos",
"Llave inglesa profesional",
"Horcas",
"Felicidad de magnitud 8",
"Me basto y me sobro",
"Hampster feliz",
"Foco Epidémico",
"¡Pandemonio mi amor!",
"¿Pandemonio? Ahh, Facil",
"Ermitaño Experimentado",
"Escritorio mal montado",
"¿Tienes fuego?",
"Era una calavera...",
"Cabeza",
"Pala de cabeza",
"Convaleciente",
"Cuerpo Sano",
"Corazones",
"Crecí en el infierno",
"¿Infierno? Desayuno esto todas las mañanas",
"¿Hola, hay alguien ahí afuera?",
"Gallinero",
"Héroe",
"La voz de los héroes",
"Acciones heroicas",
"El retorno del Héroe",
"Oye, oye, ¿quieres ver mi... pila?",
"Templo de la Suma Sacerdotisa del Sol",
"Jugador experimentado",
"¡Mantenga sus posiciones!",
"Caníbal del Holocausto",
"¡Maldita sea, un Iceberg!",
"Chaparrón bendito",
"Mi Casa",
"La casa del constructor",
"Reparador Dominguero",
"Mejoras en casa",
"Sótano laboratorio",
"Trabajador hogareño",
"Cinocéfalo",
"¡Adicto!",
"Expedicionario",
"Plano de construcción de hospital (raro)",
"Plano de construcción de hospital (inusual)",
"Plano de construcción de hospital (¡muy raro!)",
"Globo aerostático",
"Plano de construcción de hotel (raro)",
"Plano de construcción de hotel (inusual)",
"Plano de construcción de hotel (¡muy raro!)",
"Casa",
"Cuchitril",
"Hijo de cerrajero",
"Serpiente de 2 metros",
"Carne humana",
"Hundesteaks: Encargado de extinciones",
"Resaca",
"Chacal",
"Palo de Hockey",
"Hydratone 100mg",
"Red hidráulica",
"Ingeniero Hidráulico",
"No le tengo miedo a ningún fantasma",
"¡Soy una fiera!",
"¡Soy un dios! ¡Viviré por siempre!",
"El Salvador del Pueblo",
"Te estoy vigilando...",
"Ilustradora archi-maid de Pi",
"¡Puedo ver a los zombies desde aquí arriba!",
"No necesito a nadie",
"Nada se me escapa",
"¡Como clavos y cago balas!",
"Tengo un plan",
"Todavia falta un grano",
"¡Desafío aceptado!",
"Veo gente muerta",
"Pruebo todos mis productos",
"Ayer fue Serpiente Sólida...",
"Voy solo.",
"Soy alérgico a algo en el pueblo.",
"He dado la vuelta al mundo ... ¡dos veces!",
"¡Incluso busqué en el baño!",
"Tengo dolor de estómago...",
"¿Un BMW? ¡No hay problema!",
"Si son menos de 55 tragos, ¡es agua!",
"Especialidad: Puré de gato",
"Sígueme si quieres sobrevivir",
"Bricoloco",
"Libreta ilegible",
"Guía iluminado",
"¡Yo Creo!",
"Soy una leyenda",
"Estoy mareado",
"Bob el constructor",
"Inmunizado",
"Felpudo explosivo",
"¡En el fondo!",
"Beta-tester",
"Cafetera desarmada",
"Sierra eléctrica incompleta",
"Juego de cartas incompleto",
"Increíble determinación",
"Cementerio indio",
"Excavadora de agujeros grandes",
"Indiana Jones y las ruinas del Ultramundo",
"Infectado",
"Esparcidor de virus",
"Enfermería",
"Magulladuras",
"Segunda capa",
"Paladar insaciable",
"Inspiración para el pueblo",
"Manual de instrucciones",
"Insultos o mal comportamiento",
"Habitante insuperable",
"Decorador de interiores",
"Internet Explorer",
"Melón de intestino",
"¡Los bolsillos irlandeses están llenos hasta el tope!",
"Baúl de metal",
"¿Es un pajaro? Es un avion? No, ¡es el súper lanzapilas!",
"¡Es la muerte la que debería tenerme miedo!",
"Era más pequeño en el catálogo.",
"Es mejor cuando gritan.",
"Es demasiado fácil.",
"Jota",
"Bestia salvaje",
"Mesa Järpen",
"Pacificador",
"Bomba para cantimplora",
"¡Solo un dedo!",
"Yo sé cuidar mi cuerpo",
"Aguashnikov",
"Capataz",
"Guardián de los placeres",
"Guarda todo para sí mismo",
"Ganzúa",
"Rey",
"Cocina",
"Repara-fácil",
"Rata de laboratorio",
"Una etiqueta",
"Obrero",
"Laberinto",
"Master del Laberinto",
"Gran Baúl",
"Gran cortina",
"Gran paquete de regalo",
"Gran cofre de metal",
"Diodo láser",
"Último escudero",
"Último Superviviente",
"Última línea",
"¡El Último Habitante!",
"El Último Superviviente en Pandemonio",
"Cierre de último minuto",
"Cortacésped",
"Taponador de fugas",
"Campista astuto",
"Pierna",
"Maestro Domador",
"Superhéroe",
"Domador legendario",
"Ciudadano legendario",
"Guardián de los archivos",
"Luz en la noche",
"Faro",
"Escucha mi voz",
"Calabaza encendida",
"Mini-libro de meditación",
"Amigo de los animales",
"Distribuidor local",
"Cerrojo",
"Solo... estoy tan solo",
"Largavista",
"Supermercado saqueado",
"Alma errante",
"Mesías del Mundo Perdido",
"Gurú del amor",
"bajo",
"LSD",
"La pareja de baile de Lucifer",
"Suertudo",
"7 de la Suerte",
"Hallazgo",
"Jeffrey Dahmer",
"Reparador Supremo",
"Machete",
"Atomic Café",
"Llave magnética",
"Molde para llave magnética",
"Purifica la zona",
"Barricadas",
"Guitarra artesanal",
"¡Hacer que las cosas sucedan!",
"Cordon bleu del pueblo",
"¡Fuera de mi camino!",
"Mochila adicional",
"Manipulador",
"Mapa",
"MasterChef",
"Decorador con estilo",
"Martini en la playa",
"Masoquismo",
"Arquitecto",
"Constructor idealista",
"Cooking Mama",
"Gran Guardián",
"Maestro de la Inutilidad",
"Degustador",
"Descubridor",
"Caco",
"Reparador arriesgado",
"Colchón",
"Alcalde",
"¡Solo contra la Horda!",
"Cajita feliz",
"Devorador de hombres",
"Hueso con carne",
"Extractor mecánico",
"Mecanismo",
"Miembro de la Cruz Roja",
"Memoria de la civilización",
"Mensajes",
"Caja de metal",
"Vertedero de metal",
"Parches de metal",
"Estructuras metálicas",
"Minas de agua",
"Equipo de sonido",
"Minimercado «Ocxo»",
"Armería",
"No participa casi nunca",
"Ministerio de la esclavitud",
"Manguerazo",
"Teléfono móvil",
"¡Obelisco moderno!",
"Dinero para Nada",
"Caminante perdido",
"Compartimentos",
"Hostal «Hollywood Inn»",
"Aficionado motivado al festival de las hordas",
"Restaurante de autopista",
"Sandwich misterioso",
"Bizcochos enmohecidos",
"Montículo espinado",
"Demagogo",
"Brutal",
"Mi nombre es ninguno",
"Puntos de Misticismo",
"Poción chamánica",
"Transformación Mística",
"Héroe urbano",
"Neil Armstrong del Ultramundo",
"Herbicida Ness-Quick",
"Siempre se queda en casa",
"Limpio de polvo y paja",
"Nunca sin mi cubo",
"Noches en el desierto",
"Extractor con poder animal",
"Alma noble",
"Alma digna",
"Obrero Amateur",
"Norte",
"Noreste",
"Noroeste",
"¡No tengas miedo en absoluto!",
"Manimal",
"Linterna Gagdet",
"Refugio Anti-atómico",
"Carne débil",
"Objetos",
"Antiguo aeródromo",
"Taller de bicicletas",
"Vieja puerta",
"Hospital de campaña",
"Vieja Bomba hidráulica",
"Antigua comisaría",
"Santa es basura",
"Vieja lavadora",
"Trampas clásicas",
"Omnisciencia",
"Escondite de contrabandistas",
"Un ojo abierto",
"Uno para los libros",
"¡Un pueblo para gobernarlos!",
"Lata de conservas abierta",
"Chakra-Man",
"abierto",
"Cajetilla de cigarrillos abierta",
"Chocolate vencido",
"Bolsa de papas fritas rancias",
"Cadena + candado",
"Castillo",
"Pandemonio",
"Paracetoide 7g",
"Paranoico",
"Un paquete",
"Parcialmente putrefacto",
"Pueblo participante",
"Especialista en parches",
"Viga reforzada",
"Navaja",
"Unidad central",
"Dictadura del héroe",
"Miembro permanente del Club de Mickey",
"Alfombra persa",
"Productos farmacéuticos",
"CD de Phil Collins",
"Fénix del Ultramundo",
"Álbum de fotos",
"Muebles Kiela",
"Paloma del Inframundo",
"Ladron de la licorería.",
"Robamuertos",
"Saqueos en casas",
"Modelo para la comunidad",
"Bomba de humo Aroma de pino",
"Obstáculos",
"Fuselaje de avión",
"Bolsa de plástico",
"Bolsa de plástico con explosivo",
"Lanza láminas",
"Amo el olor a Cadaver remojado por la mañana",
"Buitre",
"Contrachapado",
"Compañero de bolsillo",
"Pequeño vibrador",
"Seguro para puerta",
"Oficina de correos",
"Ladrón post-mortem",
"Laboratorista autodidacta",
"Trozo de pellejo",
"Alma fuerte",
"Cámara fotográfica de post-guerra",
"Pronosticador",
"Preparen la horca, ¡vamos a colgar a Santa!",
"Pretzel",
"Medicina Preventiva",
"Pueblo privado",
"Campista Experto",
"Centinela Experto",
"Prodigio",
"Catador de productos",
"¡Probador de productos!",
"Oficio",
"Discurso motivador",
"Medium principiante",
"Alumbrado público",
"Maestro Cocinero",
"Bomba de agua",
"Agua estancada purificada",
"Calibrador PDTT Mark II",
"El trabajo es salud",
"Leña en buen estado",
"Reina",
"Habitante radiante",
"Radio casetera",
"Hombre radiactivo",
"Radius Mark II",
"Transmisor Radius",
"Perforador",
"Antepasado de Rambo",
"Jefe de muralla",
"Galletas rancias",
"Habitante prestigioso",
"Devorador de insectos",
"Reactor",
"Reciclar la vivienda",
"Actualizar",
"Sin sed",
"Suscriptor en el Sauna Pandemonio",
"Explorador de ruinas",
"Reencarnator X",
"Refuerzos metálicos",
"Refuerzos",
"Lanzamuertos",
"Gran Renovador",
"Kit de herramientas",
"Reparaciones",
"Rescate",
"Destreza",
"Revólver",
"Escudo antidisturbios",
"Pantalones rojos usados",
"Cañón de rocas",
"Equipo de música maldito",
"Mecedora",
"Rolista",
"Modo Aprendizaje",
"Tronco podrido",
"Montaña de basura",
"Mochila",
"Alarma rudimentaria",
"Ruina",
"Exploración de ruinas",
"Hombre Caterpillar",
"Cadena oxidada",
"Amante de lo ajeno",
"Sabotaje a la expedición",
"Caja fuerte",
"Casa enrejada",
"Samaritano",
"Bola de arena",
"Bolas de arena",
"Fantasma de arena",
"Conan de las arenas",
"Castillo de arena",
"Hombre de la arena",
"Sandy Maverick",
"Prensadora",
"Santa es Escoria",
"Santa es un ladrón",
"Reno de Papá Noel",
"Salvador de la humanidad",
"Bistec de serrín",
"Radar",
"Campo de espantapájaros",
"Excavador",
"Ganador Excavador del CDH",
"Caja de Schrödinger",
"Tienda Don Chicho",
"Amenaza del mundo animal",
"Explorador",
"Restos de metal",
"Despertador chillón",
"Sierra aulladora",
"Destornillador",
"Hoja de papel embarrada",
"Cofre de arquitecto sellado",
"Buscar en los deshechos",
"Barómetro",
"Precavido",
"Segundo aliento",
"Segundo Aliento",
"Chaqueta roja usada",
"Miembro de la secta",
"Hallazgo",
"Juega siempre solo",
"Explosivos",
"Cuchillo dentado",
"Con o sin llaves, yo entro",
"Barraca",
"Maestro de la oscuridad",
"Bar de mala muerte",
"Chamán",
"Lámina de metal",
"Pedazos de láminas de metal",
"Pedazo de contrachapado",
"Cerbero",
"Choque de héroes",
"Torre de tiro",
"Carrito",
"Duchas",
"Reservas de habitante precavido",
"Desterrado",
"Rincón para siesta",
"Regador Ocasional",
"Jefe de construcción",
"Muralla enjabonada",
"Arroyos",
"Cafetería",
"Defensa post-mortem",
"Empalizadas",
"Casita",
"Pala",
"Amateur",
"Lanza-mascotas",
"¿Humo? ¿Qué humo?",
"Vendedor de Arena",
"¡Mamá, no me dejes aquí!",
"¿Entonces supongo que no estamos esperando a Bob?",
"Bingo",
"Apoyo social",
"Calabaza suave",
"Rata Infame",
"Plancha de madera",
"Capataz Espiritista",
"Recolector de Almas",
"Top Chef",
"Alma de un profesional",
"Purificador de almas",
"Charlatán Profesional",
"Vendedor de almas",
"Inspirado",
"Sur",
"Sudeste",
"Sudoeste",
"Coleccionista de Recuerdos",
"Picas",
"Mascafierros",
"Tallarines chinos picantes",
"Zanja trampa",
"Muralla con púas",
"Estacas",
"Espejismo místico",
"Guía Espiritual",
"Mojador de muertos",
"Bengala",
"San Patricio",
"Pila de papeles",
"Gran estaca",
"Agua estancada",
"Lanzadardos",
"Tarta descompuesta",
"Ovación de pié",
"Estatua del Cuervo",
"Bola viscosa",
"Cañón lanzamuertos",
"Cerdo apestoso",
"Cuentacuentos",
"Un extraño aparato circular",
"Salsa picante",
"Fuerte",
"El estilo es eterno...",
"Campista suicida",
"Pistolero de agua",
"Polvo Súper-Fuzz",
"Aspirante a superhéroe",
"Manual de supervivencia",
"Ermitaño",
"Ganador Ermitaño del CDH",
"Superviviente del Infierno",
"Mosto sospechoso",
"Verdura sospechosa",
"Taller sueco",
"Venganza sórdida",
"Navaja suiza",
"Muerte a la Bokor",
"Amigo de los Animales",
"Domador",
"Táser de autodefensa",
"Delicias",
"Plato casero delicioso",
"Bistec jugoso",
"Más fuerte que Sam Fisher",
"Salteador de tabernas",
"Cleptómano",
"Técnico",
"TecnicoMecanoMegalomano",
"Osito cariñosito",
"Telescopio",
"Tienda",
"Dora la Exploradora",
"Gaudí de Zombinoia",
"Terror",
"¡Eso llevara otros 10 años!",
"El Almacén",
"El generador de batería",
"Mudanza general",
"Destornillador Humano",
"El reparador",
"¿La Gran Muralla de qué?",
"El guardia puede morir, ¡pero nunca se rinde!",
"Descuartizador",
"La hormiga humana",
"El hombre invisible",
"El último superviviente",
"Bus turístico",
"Golpe de Suerte",
"Aniquilador",
"La roca!",
"El segundo último de los mohicanos",
"El bar de las ilusiones perdidas",
"¡¡¡El cielo se está cayendo!!!",
"Furtivo",
"Ha llegado el momento de las catedrales",
"La verdad está ahí fuera en algún lugar",
"El Pozo",
"Demasiados robos cometidos",
"Hurtos",
"No hay nada a lo que no me pueda llevar esta motosierra...",
"Lanzador de Pilas",
"Una constelación lleva mi nombre",
"Sustancia espesa",
"Tercera capa",
"Sediento",
"Este duende es imparable.",
"Mil y Una Vidas",
"MuadDib",
"Bichón maltés de 3 patas",
"Simple Mortal",
"Bichón maltés cansado",
"Técnico Inagotable",
"¡Hasta el infinito y más allá!",
"Voluntario enterrado",
"Herramientas sueltas",
"Caja con cachivaches",
"Antorcha",
"Alma torturada",
"Torre",
"Pueblo",
"Biblioteca de barrio",
"Magnate del ladrillo",
"Manitas hábiles",
"Uniforme de habitante",
"Mejora del día",
"Toxina",
"Cadáver de un viajero",
"Perfidia",
"Caballete",
"Compañero de confianza",
"Explorador por accidente",
"Twinoid 500mg",
"Me siento bien",
"Tabla torcida",
"Encuentros de otro mundo",
"Consciente",
"Murazo",
"Golpeador de zombies",
"Explorador hordiano definitivo",
"Maestro Excavador",
"Mochila super-práctica",
"Indeciso",
"Cuchara-brava",
"Medicamento sin etiqueta",
"Restos irreconocibles",
"Campista inquebrantable",
"Adoquín de hormigón",
"Carne irreconocible",
"Aquí arriba",
"Catapulta mejorada",
"Mapa mejorado",
"Cinturón de herramientas",
"Inyección calmante",
"Vaporizador",
"Huerta",
"Conducto de ventilación",
"Patrocinador muy convincente",
"Frasco de veneno",
"Puñetazo salvaje",
"Festival de Videojuegos 2010",
"Proyector de cine",
"Carroñero",
"Arquitecto visionario",
"Vodka Rosquetoff",
"Máscara de vudú",
"Hechicero vudú",
"Centinel.",
"Fajo de billetes",
"Levantamuertos",
"Muralla",
"Muralla mejorada",
"Paladín",
"Aspirante a zombi...",
"Torniquete",
"Hangares",
"Guardian de las Almas",
"Centinela",
"Centinelas",
"Torre de vigilancia",
"Globo de agua",
"Perforador tectónico",
"Bombona de agua",
"Filtro de agua",
"Cañones de agua",
"Pistola de agua",
"Central hidráulica",
"Purificador de agua",
"Desinfectante efervescente",
"Ración de agua",
"Sistema de riego",
"Alma débil",
"Vertedero de armas",
"Bienvenidos al palacio. ",
"Oeste",
"¿Qué quieres decir con que estos no son caramelos?",
"¿Dónde está mi olla de oro, escurridizo ladrón?",
"Amo de la COSA",
"Hombre de Alma",
"Bestia salvaje",
"Domador de Bestias",
"Holgazan Nocturno",
"Afortunado",
"¡Ganador de corazón!",
"Ganador del CTP",
"Ejemplo para los jóvenes",
"Winness",
"Pedazo de rejilla",
"Bobina de hilo metálico",
"Falta de estimulantes",
"Sin techo ni hígado",
"Testigo de la Gran Contaminación",
"Construcción de Maravillas",
"Gran noria de Znarf",
"Maravillosamente inútil",
"Carrito cojo",
"Vertedero de madera",
"Barreras de madera",
"Valla de madera",
"Taller",
"Comegusanos",
"Maletín usado",
"Herido: Brazo",
"Herido: Ojo",
"Herido: Pie",
"Herido: Mano",
"Herido: Cabeza",
"Herido: Pierna",
"Camión averiado",
"Chatarra",
"Muñecaza de vudú",
"¡Usted no entra!",
"Tu casa es mi casa",
"Campista del Más Allá",
"Cañón de Pilas",
"Favorito de los zombies",
"Raspa-Zombies",
"Zombies eliminados",
"Zona",




"4000 zombies nos miran",
"Quinta rueda de la caravana",
"¿Dónde está Larchi?",
"¿¿¿Una caravana sin ruedas???",
"¿Una grieta? ¿Qué grieta?",
"Una carta",
"Bolsillos inteligentes",
"¡Un verdadero juego de niños!",
"Sitio de construcción abandonado",
"Parque abandonado",
"Pozo abandonado",
"Matadero",
"Ataque de pánico",
"Absenta de beber la próxima vez, ¿eh?",
"Charlatán Amateur",
"As",
"Pulverizador de ácido",
"Llave inglesa",
"Maestro de la estética",
"¡Habitante agresivo!",
"Ataque aéreo",
"Alcoholes",
"Ratero",
"Todo o nada",
"Todo el camino hasta el final y un poco más lejos",
"Mesías",
"Reparador aficionado",
"Casi!!!, ah no, ¡maldita sea!",
"Carpa diem",
"Altar",
"Laboratorista amateur",
"Ambulancia",
"Medium profesional",
"Amplificada y lista para rodar",
"Esteroides anabólicos",
"¡Y al séptimo día, no descansó!",
"Vertedero de animales",
"Cadáver animado",
"Equipo Hi-Fi defensivo",
"Placa de Sheriff",
"Repelente de Macchabees",
"Manzana",
"Manzano",
"1ro de Abril",
"Rifle de agua",
"Fuerzudo del desierto",
"Arquitecto",
"Estudio de arquitectos",
"Maletín de arquitecto",
"Maestro Rolista",
"¿Ya llegamos?",
"Armagedón",
"Lonchera",
"Testigo de Armagedón",
"Tabique de madera",
"Tabique de metal",
"Tabique grueso",
"Brazo",
"Puesto militar",
"Bandido",
"Fusil de asalto",
"Muerte por radioactividad",
"Aprietame las esposas",
"Cierre automático",
"Regaderas automáticas",
"Investigador ingenioso",
"Distinción entregada a los miembros del pueblo domador que ganó el Choque de Héroes.",
"Tengo frio aquí...",
"Saco de cemento",
"Costal de hierba fresca",
"Cebo",
"Vendaje rudimentario",
"Destierros",
"Nota de un habitante desterrado",
"Alambre de púas",
"Barney Gumble del Ultramundo",
"Pila",
"Lanzapilas 1-PDTG",
"Super lanzapilas",
"Almenas",
"Sin techo ni dientes",
"Lámpara de mesa apagada",
"Frigorífico",
"Jarra de cerveza",
"Cadáver de principiante",
"Correa",
"Hits de Elvis",
"Betapropín 5mg",
"Rastrillador del vertedero",
"Ave de mal augurio",
"Moco de cuello negro",
"Bloquea las construcciones",
"Pista bloqueada",
"Escupidor de sangre y bilis",
"Tirita ensangrentada",
"Café caliente",
"Pescador de Almas",
"Ramsés del siglo XXI",
"Lanzador de cadáveres",
"Vaporizador pro",
"Polvorín",
"Fogata",
"Dos ojos abiertos",
"Abrebotellas",
"Molde para abrebotellas",
"Cutter",
"Caja de fuegos artificiales",
"Caja de juegos",
"Caja de cerillas",
"Cajas de cartón",
"Aventurero Temerario",
"¡Gloria a la COSA!",
"Pasaje en vigor",
"Torpezas",
"Erudito",
"Quiero ser un objeto",
"CD de Britney Spears",
"Aparato electrónico descompuesto",
"Sierra de metal en mal estado",
"Hueso humano",
"Palo roto",
"Tanque averiado",
"Camaradería",
"Bruce Campbell",
"El Bruce Lee de la Espatula",
"Cañón brutal",
"El Inmortal",
"Urbanista",
"Despacho de vivienda",
"Registro de obras",
"Reparación de construcciones",
"Llave de percusión",
"Molde para llave de percusión",
"Plano de construcción de búnker (raro)",
"Plano de construcción de búnker (inusual)",
"Plano de construcción de búnker (¡muy raro!)",
"Sector inexplotable",
"Brújula andante",
"¡Quémalo, mira si sus cenizas se vuelven verdes!",
"Puntero láser potente",
"Malvaviscos quemados",
"Antorcha consumida",
"Escuela quemada",
"Carnicería",
"Cafetera",
"Camuflaje",
"Camastro",
"Acampada",
"Lata de conservas",
"Abrelatas",
"Canibalismo",
"Montículos",
"Ayudante de cocina",
"Terror de las puertas",
"Puerta de coche",
"Horno cancerígeno",
"Calabaza suave tallada",
"Adepto del SM",
"Catapulta",
"Caverna",
"Cemento y Garfunkle",
"Cafetería central",
"Laboratorio central",
"Aborigen curioso",
"Sierra eléctrica",
"Masacre de la motosierra",
"Sierras elécticas",
"Héroe popular",
"Alma caritativa",
"Che Guevara del Ultramundo",
"Vencer a la muerte",
"Jefe Excavador",
"Creador de la muerte",
"Baúl",
"Gallina",
"Jefe de Manualidades",
"Tallarines chinos",
"Pillo",
"Cruz de chocolate",
"Tronco de Navidad",
"Navidad",
"Dulce de Navidad",
"Caja sorpresa",
"Muñequito de Chuck",
"Masacrador",
"Cine",
"Habitante",
"Traficante de habitantes",
"Habitantes",
"Casa de un habitante",
"Tienda de un habitante",
"Objetos de un habitante",
"Clarividencia",
"Director ejecutivo de Clash",
"Héroe de Leyenda",
"Organización de Choque",
"Titán de choque",
"Mina antipersonal",
"Limpio",
"Saqueador",
"¡Cierra filas y aguanta!",
"cerrado",
"Tréboles",
"Lanza Muertos",
"Mina colapsada",
"Cantera derrumbada",
"Fan de X-Men",
"Cocinerillo",
"Reconocimiento de la Comunidad",
"Compañero de comunidad",
"Extremista comunitario",
"Protección civil",
"Espíritu de la comunidad",
"Hiperactivista comunitario",
"Detonador compacto",
"Ruina Man",
"Denuncias",
"Capa de hormigón",
"Plano de construcción (común)",
"Plano de construcción (raro)",
"Plano de construcción (inusual)",
"Plano de construcción (¡muy raro!)",
"Caja de materiales",
"Refugio en construcción",
"Construcciones",
"Construcciones",
"Lente convexa",
"Tubo de cobre",
"Detallista",
"Químico de barrio",
"Basurero",
"Exterminador",
"Producto corrosivo",
"Especialista en córvidos",
"Laboratorio de cosméticos",
"Lider cósmico",
"Apertura de puertas",
"Artesano",
"Pedazo de caja",
"Cremato bar",
"Cuervo navideño",
"Guirnalda de cuervo",
"Estatua del cuervo",
"Amigo de los cuervos",
"Torre de exploración",
"Crucifixión",
"Pila molida",
"Lector curioso",
"Osito cariñosito maldito",
"Equipo de música maldito",
"Cianuro",
"Perro salchicha",
"Indestructible",
"Carnada para zombies",
"Chorizo temible",
"Campista temerario",
"Bosque oscuro",
"Día",
"Linterna de luz diurna",
"¡Si me muero, mejor que sea cómodamente!",
"Ábrete Sésamo",
"Muertes por deshidratación",
"Muertes por infección",
"Muertes por abstinencia",
"Cortina de agua",
"Ilustre veterano",
"Decoración",
"Vertedero de defensas",
"Defensor",
"Defensas Max",
"Soporte de defensas",
"Colega de la deshidratacion",
"¡Deshidratado!",
"Maestro constructor demente",
"Cordon bleu del barrio",
"Zona agotada",
"Pueblo fantasma",
"Descendiente de los Atlantes",
"Historiador del desierto",
"Huérfano del desierto",
"Rata del desierto",
"Cristobal Colón",
"Empresario del Ultramundo!",
"Especulador del Ultramundo",
"Plataforma ferroviaria",
"Farmatodito destruido",
"Devastador (vacío)",
"Devastador incompleto",
"Devastador (cargado)",
"Diálisis",
"Diamantes",
"Dados",
"Dictador",
"Edificio deteriorado",
"Uniforme de habitante sucio",
"Cortacésped incompleto",
"Exploraciones avanzadas",
"Leyenda",
"Carrocerías de autos",
"Silos abandonados",
"Reciclador de almas",
"Alma Divina",
"Lanza-cohetes",
"Detector de agua",
"Maestro del Azar",
"Plato casero extraño",
"¿Fumas? Este va por mi cuenta",
"La comida para perros no sabe tan mal",
"Doggy-bag",
"No me llames junior",
"No cruces los arroyos",
"Todo terreno",
"¿No tienes algo mejor que hacer?",
"Felpudo",
"Explorador Impetuoso",
"Fan de Hannibal",
"Chicles secos",
"Malvaviscos secos",
"Taladro",
"Beber",
"Experimentaciones",
"Drogado",
"Bichón maltés eufórico",
"Estimulantes",
"Ebrio",
"Adhesivo",
"Mansión de Duke",
"Vert.",
"Vertedero mejorado",
"Recolector de basura",
"Amante del riesgo",
"Libro empolvado",
"Tapones de oído",
"Este",
"Pascua",
"Huevo de Pascua",
"Proyecto Edén",
"Edit Piaf",
"Huevo",
"Silla Ektörp-Gluten",
"Batidora eléctrica",
"Componente electrónico",
"Desterrado emancipado",
"Defensas de urgencia",
"Bidón de aceite vacío",
"Cajero vacío",
"ElectroGym",
"Una enciclopedia",
"Motor",
"Obrero Optimista",
"Predicador iluminado",
"Un sobre",
"Igual a Chuck Norris",
"Trincheras militares",
"Claviceps Purpurea",
"Cidra claviceps artesanal",
"Escolta",
"Eterno segundo",
"Todo para mi boca",
"Muralla evolutiva",
"Desmonte",
"Consume demasiada agua",
"Cansado",
"Cansado",
"Explorador impetuosísimo",
"Exploraciones muy lejanas",
"Pomelo explosivo",
"Bolsa de agua explosiva",
"Mutilador",
"Amor extra grande",
"Habitante fuera de serie",
"Muro extra",
"Cocina exótica",
"Caminante del Horizonte",
"Proyectos delirantes",
"Ojo",
"Ojo del Ultramundo",
"Fábrica",
"Stand de feria de atracciones",
"Fondo Falso",
"Pueblo falso",
"Cripta familiar",
"Restaurante «Burger Twin»",
"Gato bonito",
"Serpiente agonizante",
"Santa es un pillo",
"Maldito Papá Noel",
"Grifería",
"Gran Noria de Znarf",
"Viajero sin miedo",
"Sin hambre",
"Valla",
"Fertilizante",
"Pellejo humano",
"Combates mortales",
"Llenar",
"Fuegos artificiales",
"Tubo de lanzamiento de fuegos artificiales",
"Manitas hábiles",
"Carne de cañón FJV08",
"Bomba de carnaval",
"Pólvora brillante",
"Mueble para armar",
"Huir",
"Canalla",
"Puré de hongos carroñeros",
"Hongos carroñeros",
"Vertedero de comida",
"Caja de alimentos",
"Pie",
"Fortificaciones",
"Gorro rojo maloliente",
"Traje de Papá Noel",
"Cimientos",
"Obrero Iluminado",
"Sándwiches «San Guchito»",
"Fiesta en casa",
"¡Habitante libre!",
"Vertedero gratuito",
"Comerciante de carne fresca",
"Omnívoro",
"Ingeniero de Fruit Loop",
"Cantimplora llena",
"Lleno de proteínas.",
"Especialista en reasignación de fondos",
"Gatito furioso",
"Horca",
"Vertedero público",
"Cabaña de jardín",
"Cañón aspirina",
"Boletín",
"Rastreador friki",
"Generosidad",
"Abridor de puertas",
"Ponga cinta adhesiva allí.",
"¡Mutante!",
"Vacuna para mutante",
"Gran COSA",
"Rata gigante",
"Gran Castillo de Arena",
"Paquete de regalo",
"¡Dame un trago o el perro sufrira las consecuencias!",
"Fama",
"¡Gloria al cuervo!",
"Cadáver carcomido",
"Mordedor de muertos",
"Gurú Rico",
"¿Un chorrito más señor?",
"Tomb Raider",
"Buen chico",
"Habitante con buen gusto",
"Gran maestro de llaves",
"Pomelo explosivo",
"Muro de faquir",
"Constructor visionario",
"Gran Eremita independiente",
"Arquitecto estrambótico",
"Gran charco",
"Zanja periférica",
"Albañil Dominguero",
"Vodka Rosquetoff",
"Traje de duendecillo",
"Bomba macabra",
"Tela de carpa",
"Perro guardián",
"Guardia de las focas",
"Torre de guardia",
"Guardián",
"Campeón de Choque de héroes",
"Trampas de guerrilla",
"Guía del Ultramundo",
"Conejillo de Indias",
"Armería GunsnZombies",
"Especialista con armas de agua",
"Sierra de metal",
"Alitas de pollo mordidas",
"Halloween",
"Hammam",
"Mano",
"Puñado de balas",
"Puñado de tornillos y tuercas",
"Puñado de caramelos",
"Llave inglesa profesional",
"Horcas",
"Felicidad de magnitud 8",
"Me basto y me sobro",
"Hampster feliz",
"Foco Epidémico",
"¡Pandemonio mi amor!",
"¿Pandemonio? Ahh, Facil",
"Ermitaño Experimentado",
"Escritorio mal montado",
"¿Tienes fuego?",
"Era una calavera...",
"Cabeza",
"Pala de cabeza",
"Convaleciente",
"Cuerpo Sano",
"Corazones",
"Crecí en el infierno",
"¿Infierno? Desayuno esto todas las mañanas",
"¿Hola, hay alguien ahí afuera?",
"Gallinero",
"Héroe",
"La voz de los héroes",
"Acciones heroicas",
"El retorno del Héroe",
"Oye, oye, ¿quieres ver mi... pila?",
"Templo de la Suma Sacerdotisa del Sol",
"Jugador experimentado",
"¡Mantenga sus posiciones!",
"Caníbal del Holocausto",
"¡Maldita sea, un Iceberg!",
"Chaparrón bendito",
"Mi Casa",
"La casa del constructor",
"Reparador Dominguero",
"Mejoras en casa",
"Sótano laboratorio",
"Trabajador hogareño",
"Cinocéfalo",
"¡Adicto!",
"Expedicionario",
"Plano de construcción de hospital (raro)",
"Plano de construcción de hospital (inusual)",
"Plano de construcción de hospital (¡muy raro!)",
"Globo aerostático",
"Plano de construcción de hotel (raro)",
"Plano de construcción de hotel (inusual)",
"Plano de construcción de hotel (¡muy raro!)",
"Casa",
"Cuchitril",
"Hijo de cerrajero",
"Serpiente de 2 metros",
"Carne humana",
"Hundesteaks: Encargado de extinciones",
"Resaca",
"Chacal",
"Palo de Hockey",
"Hydratone 100mg",
"Red hidráulica",
"Ingeniero Hidráulico",
"No le tengo miedo a ningún fantasma",
"¡Soy una fiera!",
"¡Soy un dios! ¡Viviré por siempre!",
"El Salvador del Pueblo",
"Te estoy vigilando...",
"Ilustradora archi-maid de Pi",
"¡Puedo ver a los zombies desde aquí arriba!",
"No necesito a nadie",
"Nada se me escapa",
"¡Como clavos y cago balas!",
"Tengo un plan",
"Todavia falta un grano",
"¡Desafío aceptado!",
"Veo gente muerta",
"Pruebo todos mis productos",
"Ayer fue Serpiente Sólida...",
"Voy solo.",
"Soy alérgico a algo en el pueblo.",
"He dado la vuelta al mundo ... ¡dos veces!",
"¡Incluso busqué en el baño!",
"Tengo dolor de estómago...",
"¿Un BMW? ¡No hay problema!",
"Si son menos de 55 tragos, ¡es agua!",
"Especialidad: Puré de gato",
"Sígueme si quieres sobrevivir",
"Bricoloco",
"Libreta ilegible",
"Guía iluminado",
"¡Yo Creo!",
"Soy una leyenda",
"Estoy mareado",
"Bob el constructor",
"Inmunizado",
"Felpudo explosivo",
"¡En el fondo!",
"Beta-tester",
"Cafetera desarmada",
"Sierra eléctrica incompleta",
"Juego de cartas incompleto",
"Increíble determinación",
"Cementerio indio",
"Excavadora de agujeros grandes",
"Indiana Jones y las ruinas del Ultramundo",
"Infectado",
"Esparcidor de virus",
"Enfermería",
"Magulladuras",
"Segunda capa",
"Paladar insaciable",
"Inspiración para el pueblo",
"Manual de instrucciones",
"Insultos o mal comportamiento",
"Habitante insuperable",
"Decorador de interiores",
"Internet Explorer",
"Melón de intestino",
"¡Los bolsillos irlandeses están llenos hasta el tope!",
"Baúl de metal",
"¿Es un pajaro? Es un avion? No, ¡es el súper lanzapilas!",
"¡Es la muerte la que debería tenerme miedo!",
"Era más pequeño en el catálogo.",
"Es mejor cuando gritan.",
"Es demasiado fácil.",
"Jota",
"Bestia salvaje",
"Mesa Järpen",
"Pacificador",
"Bomba para cantimplora",
"¡Solo un dedo!",
"Yo sé cuidar mi cuerpo",
"Aguashnikov",
"Capataz",
"Guardián de los placeres",
"Guarda todo para sí mismo",
"Ganzúa",
"Rey",
"Cocina",
"Repara-fácil",
"Rata de laboratorio",
"Una etiqueta",
"Obrero",
"Laberinto",
"Master del Laberinto",
"Gran Baúl",
"Gran cortina",
"Gran paquete de regalo",
"Gran cofre de metal",
"Diodo láser",
"Último escudero",
"Último Superviviente",
"Última línea",
"¡El Último Habitante!",
"El Último Superviviente en Pandemonio",
"Cierre de último minuto",
"Cortacésped",
"Taponador de fugas",
"Campista astuto",
"Pierna",
"Maestro Domador",
"Superhéroe",
"Domador legendario",
"Ciudadano legendario",
"Guardián de los archivos",
"Luz en la noche",
"Faro",
"Escucha mi voz",
"Calabaza encendida",
"Mini-libro de meditación",
"Amigo de los animales",
"Distribuidor local",
"Cerrojo",
"Solo... estoy tan solo",
"Largavista",
"Supermercado saqueado",
"Alma errante",
"Mesías del Mundo Perdido",
"Gurú del amor",
"bajo",
"LSD",
"La pareja de baile de Lucifer",
"Suertudo",
"7 de la Suerte",
"Hallazgo",
"Jeffrey Dahmer",
"Reparador Supremo",
"Machete",
"Atomic Café",
"Llave magnética",
"Molde para llave magnética",
"Purifica la zona",
"Barricadas",
"Guitarra artesanal",
"¡Hacer que las cosas sucedan!",
"Cordon bleu del pueblo",
"¡Fuera de mi camino!",
"Mochila adicional",
"Manipulador",
"Mapa",
"MasterChef",
"Decorador con estilo",
"Martini en la playa",
"Masoquismo",
"Arquitecto",
"Constructor idealista",
"Cooking Mama",
"Gran Guardián",
"Maestro de la Inutilidad",
"Degustador",
"Descubridor",
"Caco",
"Reparador arriesgado",
"Colchón",
"Alcalde",
"¡Solo contra la Horda!",
"Cajita feliz",
"Devorador de hombres",
"Hueso con carne",
"Extractor mecánico",
"Mecanismo",
"Miembro de la Cruz Roja",
"Memoria de la civilización",
"Mensajes",
"Caja de metal",
"Vertedero de metal",
"Parches de metal",
"Estructuras metálicas",
"Minas de agua",
"Equipo de sonido",
"Minimercado «Ocxo»",
"Armería",
"No participa casi nunca",
"Ministerio de la esclavitud",
"Manguerazo",
"Teléfono móvil",
"¡Obelisco moderno!",
"Dinero para Nada",
"Caminante perdido",
"Compartimentos",
"Hostal «Hollywood Inn»",
"Aficionado motivado al festival de las hordas",
"Restaurante de autopista",
"Sandwich misterioso",
"Bizcochos enmohecidos",
"Montículo espinado",
"Demagogo",
"Brutal",
"Mi nombre es ninguno",
"Puntos de Misticismo",
"Poción chamánica",
"Transformación Mística",
"Héroe urbano",
"Neil Armstrong del Ultramundo",
"Herbicida Ness-Quick",
"Siempre se queda en casa",
"Limpio de polvo y paja",
"Nunca sin mi cubo",
"Noches en el desierto",
"Extractor con poder animal",
"Alma noble",
"Alma digna",
"Obrero Amateur",
"Norte",
"Noreste",
"Noroeste",
"¡No tengas miedo en absoluto!",
"Manimal",
"Linterna Gagdet",
"Refugio Anti-atómico",
"Carne débil",
"Objetos",
"Antiguo aeródromo",
"Taller de bicicletas",
"Vieja puerta",
"Hospital de campaña",
"Vieja Bomba hidráulica",
"Antigua comisaría",
"Santa es basura",
"Vieja lavadora",
"Trampas clásicas",
"Omnisciencia",
"Escondite de contrabandistas",
"Un ojo abierto",
"Uno para los libros",
"¡Un pueblo para gobernarlos!",
"Lata de conservas abierta",
"Chakra-Man",
"abierto",
"Cajetilla de cigarrillos abierta",
"Chocolate vencido",
"Bolsa de papas fritas rancias",
"Cadena + candado",
"Castillo",
"Pandemonio",
"Paracetoide 7g",
"Paranoico",
"Un paquete",
"Parcialmente putrefacto",
"Pueblo participante",
"Especialista en parches",
"Viga reforzada",
"Navaja",
"Unidad central",
"Dictadura del héroe",
"Miembro permanente del Club de Mickey",
"Alfombra persa",
"Productos farmacéuticos",
"CD de Phil Collins",
"Fénix del Ultramundo",
"Álbum de fotos",
"Muebles Kiela",
"Paloma del Inframundo",
"Ladron de la licorería.",
"Robamuertos",
"Saqueos en casas",
"Modelo para la comunidad",
"Bomba de humo Aroma de pino",
"Obstáculos",
"Fuselaje de avión",
"Bolsa de plástico",
"Bolsa de plástico con explosivo",
"Lanza láminas",
"Amo el olor a Cadaver remojado por la mañana",
"Buitre",
"Contrachapado",
"Compañero de bolsillo",
"Pequeño vibrador",
"Seguro para puerta",
"Oficina de correos",
"Ladrón post-mortem",
"Laboratorista autodidacta",
"Trozo de pellejo",
"Alma fuerte",
"Cámara fotográfica de post-guerra",
"Pronosticador",
"Preparen la horca, ¡vamos a colgar a Santa!",
"Pretzel",
"Medicina Preventiva",
"Pueblo privado",
"Campista Experto",
"Centinela Experto",
"Prodigio",
"Catador de productos",
"¡Probador de productos!",
"Oficio",
"Discurso motivador",
"Medium principiante",
"Alumbrado público",
"Maestro Cocinero",
"Bomba de agua",
"Agua estancada purificada",
"Calibrador PDTT Mark II",
"El trabajo es salud",
"Leña en buen estado",
"Reina",
"Habitante radiante",
"Radio casetera",
"Hombre radiactivo",
"Radius Mark II",
"Transmisor Radius",
"Perforador",
"Antepasado de Rambo",
"Jefe de muralla",
"Galletas rancias",
"Habitante prestigioso",
"Devorador de insectos",
"Reactor",
"Reciclar la vivienda",
"Actualizar",
"Sin sed",
"Suscriptor en el Sauna Pandemonio",
"Explorador de ruinas",
"Reencarnator X",
"Refuerzos metálicos",
"Refuerzos",
"Lanzamuertos",
"Gran Renovador",
"Kit de herramientas",
"Reparaciones",
"Rescate",
"Destreza",
"Revólver",
"Escudo antidisturbios",
"Pantalones rojos usados",
"Cañón de rocas",
"Equipo de música maldito",
"Mecedora",
"Rolista",
"Modo Aprendizaje",
"Tronco podrido",
"Montaña de basura",
"Mochila",
"Alarma rudimentaria",
"Ruina",
"Exploración de ruinas",
"Hombre Caterpillar",
"Cadena oxidada",
"Amante de lo ajeno",
"Sabotaje a la expedición",
"Caja fuerte",
"Casa enrejada",
"Samaritano",
"Bola de arena",
"Bolas de arena",
"Fantasma de arena",
"Conan de las arenas",
"Castillo de arena",
"Hombre de la arena",
"Sandy Maverick",
"Prensadora",
"Santa es Escoria",
"Santa es un ladrón",
"Reno de Papá Noel",
"Salvador de la humanidad",
"Bistec de serrín",
"Radar",
"Campo de espantapájaros",
"Excavador",
"Ganador Excavador del CDH",
"Caja de Schrödinger",
"Tienda Don Chicho",
"Amenaza del mundo animal",
"Explorador",
"Restos de metal",
"Despertador chillón",
"Sierra aulladora",
"Destornillador",
"Hoja de papel embarrada",
"Cofre de arquitecto sellado",
"Buscar en los deshechos",
"Barómetro",
"Precavido",
"Segundo aliento",
"Segundo Aliento",
"Chaqueta roja usada",
"Miembro de la secta",
"Hallazgo",
"Juega siempre solo",
"Explosivos",
"Cuchillo dentado",
"Con o sin llaves, yo entro",
"Barraca",
"Maestro de la oscuridad",
"Bar de mala muerte",
"Chamán",
"Lámina de metal",
"Pedazos de láminas de metal",
"Pedazo de contrachapado",
"Cerbero",
"Choque de héroes",
"Torre de tiro",
"Carrito",
"Duchas",
"Reservas de habitante precavido",
"Desterrado",
"Rincón para siesta",
"Regador Ocasional",
"Jefe de construcción",
"Muralla enjabonada",
"Arroyos",
"Cafetería",
"Defensa post-mortem",
"Empalizadas",
"Casita",
"Pala",
"Amateur",
"Lanza-mascotas",
"¿Humo? ¿Qué humo?",
"Vendedor de Arena",
"¡Mamá, no me dejes aquí!",
"¿Entonces supongo que no estamos esperando a Bob?",
"Bingo",
"Apoyo social",
"Calabaza suave",
"Rata Infame",
"Plancha de madera",
"Capataz Espiritista",
"Recolector de Almas",
"Top Chef",
"Alma de un profesional",
"Purificador de almas",
"Charlatán Profesional",
"Vendedor de almas",
"Inspirado",
"Sur",
"Sudeste",
"Sudoeste",
"Coleccionista de Recuerdos",
"Picas",
"Mascafierros",
"Tallarines chinos picantes",
"Zanja trampa",
"Muralla con púas",
"Estacas",
"Espejismo místico",
"Guía Espiritual",
"Mojador de muertos",
"Bengala",
"San Patricio",
"Pila de papeles",
"Gran estaca",
"Agua estancada",
"Lanzadardos",
"Tarta descompuesta",
"Ovación de pié",
"Estatua del Cuervo",
"Bola viscosa",
"Cañón lanzamuertos",
"Cerdo apestoso",
"Cuentacuentos",
"Un extraño aparato circular",
"Salsa picante",
"Fuerte",
"El estilo es eterno...",
"Campista suicida",
"Pistolero de agua",
"Polvo Súper-Fuzz",
"Aspirante a superhéroe",
"Manual de supervivencia",
"Ermitaño",
"Ganador Ermitaño del CDH",
"Superviviente del Infierno",
"Mosto sospechoso",
"Verdura sospechosa",
"Taller sueco",
"Venganza sórdida",
"Navaja suiza",
"Muerte a la Bokor",
"Amigo de los Animales",
"Domador",
"Táser de autodefensa",
"Delicias",
"Plato casero delicioso",
"Bistec jugoso",
"Más fuerte que Sam Fisher",
"Salteador de tabernas",
"Cleptómano",
"Técnico",
"TecnicoMecanoMegalomano",
"Osito cariñosito",
"Telescopio",
"Tienda",
"Dora la Exploradora",
"Gaudí de Zombinoia",
"Terror",
"¡Eso llevara otros 10 años!",
"El Almacén",
"El generador de batería",
"Mudanza general",
"Destornillador Humano",
"El reparador",
"¿La Gran Muralla de qué?",
"El guardia puede morir, ¡pero nunca se rinde!",
"Descuartizador",
"La hormiga humana",
"El hombre invisible",
"El último superviviente",
"Bus turístico",
"Golpe de Suerte",
"Aniquilador",
"La roca!",
"El segundo último de los mohicanos",
"El bar de las ilusiones perdidas",
"¡¡¡El cielo se está cayendo!!!",
"Furtivo",
"Ha llegado el momento de las catedrales",
"La verdad está ahí fuera en algún lugar",
"El Pozo",
"Demasiados robos cometidos",
"Hurtos",
"No hay nada a lo que no me pueda llevar esta motosierra...",
"Lanzador de Pilas",
"Una constelación lleva mi nombre",
"Sustancia espesa",
"Tercera capa",
"Sediento",
"Este duende es imparable.",
"Mil y Una Vidas",
"MuadDib",
"Bichón maltés de 3 patas",
"Simple Mortal",
"Bichón maltés cansado",
"Técnico Inagotable",
"¡Hasta el infinito y más allá!",
"Voluntario enterrado",
"Herramientas sueltas",
"Caja con cachivaches",
"Antorcha",
"Alma torturada",
"Torre",
"Pueblo",
"Biblioteca de barrio",
"Magnate del ladrillo",
"Manitas hábiles",
"Uniforme de habitante",
"Mejora del día",
"Toxina",
"Cadáver de un viajero",
"Perfidia",
"Caballete",
"Compañero de confianza",
"Explorador por accidente",
"Twinoid 500mg",
"Me siento bien",
"Tabla torcida",
"Encuentros de otro mundo",
"Consciente",
"Murazo",
"Golpeador de zombies",
"Explorador hordiano definitivo",
"Maestro Excavador",
"Mochila super-práctica",
"Indeciso",
"Cuchara-brava",
"Medicamento sin etiqueta",
"Restos irreconocibles",
"Campista inquebrantable",
"Adoquín de hormigón",
"Carne irreconocible",
"Aquí arriba",
"Catapulta mejorada",
"Mapa mejorado",
"Cinturón de herramientas",
"Inyección calmante",
"Vaporizador",
"Huerta",
"Conducto de ventilación",
"Patrocinador muy convincente",
"Frasco de veneno",
"Puñetazo salvaje",
"Festival de Videojuegos 2010",
"Proyector de cine",
"Carroñero",
"Arquitecto visionario",
"Vodka Rosquetoff",
"Máscara de vudú",
"Hechicero vudú",
"Centinel.",
"Fajo de billetes",
"Levantamuertos",
"Muralla",
"Muralla mejorada",
"Paladín",
"Aspirante a zombi...",
"Torniquete",
"Hangares",
"Guardian de las Almas",
"Centinela",
"Centinelas",
"Torre de vigilancia",
"Globo de agua",
"Perforador tectónico",
"Bombona de agua",
"Filtro de agua",
"Cañones de agua",
"Pistola de agua",
"Central hidráulica",
"Purificador de agua",
"Desinfectante efervescente",
"Ración de agua",
"Sistema de riego",
"Alma débil",
"Vertedero de armas",
"Bienvenidos al palacio. ",
"Oeste",
"¿Qué quieres decir con que estos no son caramelos?",
"¿Dónde está mi olla de oro, escurridizo ladrón?",
"Amo de la COSA",
"Hombre de Alma",
"Bestia salvaje",
"Domador de Bestias",
"Holgazan Nocturno",
"Afortunado",
"¡Ganador de corazón!",
"Ganador del CTP",
"Ejemplo para los jóvenes",
"Winness",
"Pedazo de rejilla",
"Bobina de hilo metálico",
"Falta de estimulantes",
"Sin techo ni hígado",
"Testigo de la Gran Contaminación",
"Construcción de Maravillas",
"Gran noria de Znarf",
"Maravillosamente inútil",
"Carrito cojo",
"Vertedero de madera",
"Barreras de madera",
"Valla de madera",
"Taller",
"Comegusanos",
"Maletín usado",
"Herido: Brazo",
"Herido: Ojo",
"Herido: Pie",
"Herido: Mano",
"Herido: Cabeza",
"Herido: Pierna",
"Camión averiado",
"Chatarra",
"Muñecaza de vudú",
"¡Usted no entra!",
"Tu casa es mi casa",
"Campista del Más Allá",
"Cañón de Pilas",
"Favorito de los zombies",
"Raspa-Zombies",
"Zombies eliminados",
"Zona",
"Jarra De Cerveza",
"Perro Salchicha Pulgoso",
"Retroproyector Antiguo",
"Pretzel Arenoso",
"Palo De Hurling Clásico",
"Pinta Pegajosa",
"Medalla De Un Soldado"];
module.exports = {array}
