export let array = [
"4000 Zombies starren uns an",
"5. Rad am Wagen",
"Où est Larchi ?",
"Ein Wohnwagen ohne Räder???",
"Ein Riss? Welcher Riss?",
"Ein Brief ohne Adresse",
"Aufgeräumte Tasche",
"Ein Spiel für echte Kinder",
"Verlassene Baustelle",
"Verwilderter Park",
"Verlassener Brunnen",
"Schlachthof",
"Nackte Panik",
"Fass das Saufen lieber sein",
"Schlimmer Finger",
"Ass",
"Säurespray",
"Verstellbarer Schraubenschlüssel",
"Ordnung muss sein!",
"Aggressiver Mitbürger",
"Luftschlag",
"Alkohol",
"Dieb",
"Alles oder nichts",
"Bis zum Ende und einen Schritt weiter",
"Messias",
"Gewissenhafter Maurer",
"Faaaaaaaast, ach verdammt",
"Allein in dieser Welt",
"Altar",
"Amateur-Laborratte",
"Krankenwagen",
"Amophilis Psychotropes",
"Aufgeladen und kampfbereit",
"Anaboles Steroid",
"Am 7. Tag erschuf er den Fleischkäfig",
"Tierabfälle",
"Sudoku ist anders",
"Verteidigende HiFi",
"ANZAC Badge",
"Maccabees-Vertreiber",
"Apfel",
"Apfelbaum",
"1. April",
"Aqua-Splash",
"Archäologielehrling",
"Architekt",
"Bauhaus",
"Architektenkoffer",
"Archivar",
"Sind wir schon da?",
"Armageddon",
"Lunch-Box",
"Zeuge des Armageddon",
"Rüstungsplatten",
"Rüstungsplatten 2.0",
"Rüstungsplatten 3.0",
"Arme",
"Militärischer Wachposten",
"Lump",
"Sturmgewehr",
"Tod durch Radioaktivität",
"Nenn mich Herrin",
"Kolbenschließmechanismus",
"Sprinkleranlage",
"Autonomer Müll",
"Auszeichnung für die Mitglieder der Dompteuren-Liga, die beim Shock of Heroes Event gewonnen haben!",
"Mir ist kalt hier draußen...",
"Zementsack",
"Trockene Kräuter",
"Köder",
"Bandage",
"Verbannungen",
"Notizzettel eines Verbannten",
"Stacheldraht",
"Barney Gumble der Außenwelt",
"Batterie",
"Batteriewerfer 1-PDTG",
"Batteriewerferfabrikant",
"Brustwehr",
"Runaway Michael",
"Ausgeschaltete Nachttischlampe",
"Minibar",
"Bierkrug",
"Anfängerleiche",
"Riemen",
"Best of The King CD",
"Betapropin-Tablette 5mg",
"Abstauber",
"Vogel der schlechten Vorzeichen",
"Schwarzer Zervixschleim",
"Blockiert die Baustelle",
"Versperrte Straße",
"Gedärmeauskotzer",
"Blutdurchtränkter Verband",
"Heißer Kaffee",
"Blauer Feuerspucker",
"Oscar Niemeyer",
"Erfahrener Müllmann",
"Kärcher",
"Sprengfalle",
"Leuchtfeuer",
"Mit offenen Augen schlafen? Kein Problem!",
"Flaschenöffner",
"Abdruck vom Flaschenöffner",
"Teppichmesser",
"Feuerwerkskiste",
"Gesellschaftsspiel",
"Streichholzschachtel",
"Kartons",
"Wikinger",
"Huldigt den riesigen KVF!",
"Durchgang in Kraft",
"Schusseligkeiten",
"Panzerschrank",
"Ich möchte dein Objekt sein.",
"Britney Spears CD",
"Defektes Elektrogerät",
"Beschädigte Metallsäge",
"Angeknackster menschlicher Knochen",
"Kaputter Stock",
"Liegengebliebener Kampfpanzer",
"Freundschaft",
"Bruce Campbell",
"Der Bruce Lee des Spachtels",
"Brutale Kanone",
"Buddha",
"Maurer",
"Baumarkt",
"Baustellenbuch",
"Gebäudereparaturen",
"Schlagschlüssel",
"Abdruck vom Schlagschlüssel",
"Bunker-Bauplan (selten)",
"Bunker-Bauplan (ungewöhnlich)",
"Bunker-Bauplan (sehr selten!)",
"Verschüttete Ruine",
"Inklusive Kompass",
"Verbrennt ihn! Sieh nach ob seine Asche grün wird!",
"Starker Laserpointer",
"Geröstete Marshmallows",
"Verbrauchte Fackel",
"Verbrannte Grundschule",
"Metzger",
"Kaffeekocher",
"Tarnanzug",
"Feldbett",
"Camping",
"Konservendose",
"Dosenöffner",
"Kannibalismus",
"Kanonenhügel",
"Kantinenkoch",
"Schlüsseldienst",
"Autotür",
"Krebserregender Ofen",
"Ausgeschnitzter weicher Kürbis",
"SM Anhänger",
"Katapult",
"Höhle",
"Zement & Garfunkel",
"Kantine",
"Labor",
"Diplomierter Scharlatan",
"Kettensäge",
"Kettensägenmassaker",
"Kettensägen",
"Volksheld",
"Immer zur Stelle",
"Che Guevara der Wüste",
"Den Tod besiegen",
"Großer Ameisenbär",
"Totmacher",
"Truhe",
"Huhn",
"Das Unnütze mit dem Angenehmen verbinden",
"Chinesische Nudeln",
"Schaumschläger",
"Schokoladenkreuz",
"Logbuch Schokolade",
"Weihnachten",
"Weihnachts-Süßigkeiten",
"Überraschungskiste",
"Chuck-Figur",
"Schlächter",
"Kino",
"Einwohner",
"Überzeugender Guru",
"Bürger",
"Abgelegenes Haus",
"Zelt eines Bürgers",
"Habseligkeiten eines Bürgers",
"Hellseherei",
"Clash CEO",
"Ultimativer Tod des SoH",
"Community-Auszeichnung",
"Schlachtenbummler",
"Tretmine",
"Clean",
"Kleptomane",
"Schließt die Ränke und haltet durch",
"geschlossen",
"Kreuz",
"Sarg-Katapult",
"Eingestürzte Mine",
"Eingestürzter Steinbruch",
"X-Men Leser",
"Kleiner Küchenchef",
"Event-Auszeichnungen",
"Jedes Los gewinnt",
"Gemeinschaftsfreak",
"Bollwerk",
"Zinker",
"Siebenseitiger Würfel",
"Zünder",
"Im Irrgarten",
"Anzeigen",
"Betonschicht",
"Normaler Bauplan (gewöhnlich)",
"Normaler Bauplan (selten)",
"Normaler Bauplan (ungewöhnlich)",
"Normaler Bauplan (sehr selten!)",
"Kiste mit Materialien",
"Baustellencontainer",
"Konstruktionen",
"Baustellen",
"Konvexlinse",
"Kupferrohr",
"Ästhet",
"Chemiker von um die Ecke",
"Müllmann",
"Killer",
"Ätzmittel",
"Corvid-Spezialist",
"Kosmetiklabor",
"Kosmischer Anführer",
"Geöffnete Tür",
"Handwerk",
"Holzkistendeckel",
"Kremato-Cue",
"Krähenelfe",
"Krähengirlande",
"Krähenstatue",
"Rabenfreund",
"Krähennest",
"Kreuzigung",
"Zerquetschte Batterie",
"Neugieriger Leser",
"Verfluchter Teddybär",
"Verfluchte HiFi",
"Zyanid",
"Dackel",
"Unzerstörbar",
"Der mit den Zombies tanzt",
"Ali Baba",
"Mutiger Camper",
"Dunkler Hain",
"Tag",
"Wegweiser",
"In deinem Bett gestorben",
"Türöffner",
"Dehydrationstode",
"Tödliche Infektionen",
"Tod durch Entzug",
"Wasserfall",
"Berühmter Veteran",
"Dekoration",
"Rüstungsabfall",
"Die Mauer",
"Verteidigungsanlage",
"Pentagon",
"Dehydrationskollege",
"Dehydriert",
"Hirnverbrannter Baumeister",
"Meister Eintopf",
"Zone leer",
"Verfallene Villa",
"Abstieg der Atlanteaner",
"Wüstenhistoriker",
"Waisenkind der Wüste",
"Riesenmaulwurf",
"Christopher Kolumbus",
"Showman aus der Anderen Welt!",
"Wüstenspekulant",
"Alter Rangierbahnhof",
"Zerstörte Apotheke",
"Zerstörer (entladen)",
"Unvollständiger Zerstörer",
"Zerstörer (geladen)",
"Dialyse",
"Karo",
"Ein paar Würfel",
"Diktator",
"Verfallenes Bürogebäude",
"Dreckige Bürgerbekleidung",
"Zerlegter Rasenmäher",
"Komplexe Expeditionen",
"Entfernte Regionen",
"Autowracks",
"Verlassene Silos",
"Mystischer Seher",
"Göttliche Seele",
"Wünschelrakete",
"Wünschelrute",
"Vierklettriges Kleeblatt",
"Verdächtige Speise",
"Rauchts? Dann ist es meins.",
"Hundewurst schmeckt gar nicht schlecht!",
"Doggybag",
"Labyrinth-Meister MB",
"Lebenssammler",
"Ich komme heute Nacht nicht heim...",
"Hast du nichts besseres zu tun?",
"Fußabstreifer",
"Stürmischer Kundschafter",
"Hannibalfan",
"Trockene Kaugummis",
"Getrocknete Marshmallows",
"Brunnenbohrer",
"Trinken",
"Drogenerfahrungen",
"Rauschzustand",
"Malteser Hündchen auf Droge",
"Drogen",
"Trunkenheit",
"Klebeband",
"Dukes Villa",
"Müllhalde",
"Verbesserte Müllhalde",
"Müllkind",
"Green Beret",
"Staubiges Buch",
"Ohrstöpsel",
"Osten",
"Ostern",
"Osterei",
"Projekt Eden",
"Edit Piaf",
"Ei",
"Ektorp-Gluten Stuhl",
"Handmixer",
"Elektronisches Bauteil",
"Autarker Verbannter",
"Notfallkonstruktion",
"Ölkännchen",
"Leerer Automat",
"Elektrischer Bauchmuskeltrainer",
"Eine Enzyklopädie",
"Motor",
"Erleuchteter Baumeister",
"Erleuchteter Prediger",
"Ein Briefumschlag",
"Chuck Norris Ebenbild",
"Schützengraben",
"Mutterkorn",
"Korn-Bräu",
"Eskorte",
"Ewiger Zweiter",
"Alles für meinen Mund",
"Entwicklungsfähige Stadtmauer",
"Ausgrabungsarbeiten",
"Verbraucht zuviel Wasser",
"Erschöpfung",
"Erschöpft",
"Draufgängerischer Expeditionsreisender",
"Expertenexpeditionen",
"Explosive Pampelmuse",
"Explodierende Wasserbombe",
"Verstümmler",
"Extra viel Liebe",
"Aussergewöhnlicher Bürger",
"Extramauer",
"Grillmeister",
"Lebensmüder Kundschafter",
"Absurde Projekte",
"Auge",
"Auge der Wüste",
"Manufaktur",
"Jahrmarktstand",
"Doppelter Boden",
"Falsche Stadt",
"Familiengrab",
"Fast Food Restaurant",
"Großer knuddeliger Kater",
"Fette Python",
"Der Weihnachtsmann ist ein Schlawiner",
"Den Weihnachtsmann gibt es nicht",
"Wasserhahn",
"Rad des Schreckens",
"Furchtloser Abenteurer",
"Satt",
"Zaun (Haus)",
"Dünger",
"Ekliger Hautfetzen",
"Kämpfe um Leben und Tod",
"Befüllen",
"Feuerwerk",
"Flush-Abschussrohr",
"Meisterbastler ",
"FJV08 Kanonenfutter",
"Schießpulverbombe",
"Raketenpulver",
"Möbelpackung",
"Flüchten",
"Kojote der kargen Steppen",
"Aasbeerenbrei",
"Aasbeeren",
"Biomüll",
"Nahrungsmittelkiste",
"Fuß",
"Befestigungen",
"Schweißtriefende rote Mütze",
"Übelriechender Anzug aus einer anderen Zeit",
"Fundament",
"Erbauer der verlorenen Zeit",
"Dönerbude Utsel-Brutzel",
"Dollhouse",
"Freier Bürger",
"Müll für Alle",
"Frischfleischhändler",
"Ich brauche niemanden!",
"Vereister Ingenieur",
"Kanister",
"Die Macht der Proteine",
"Kleiner Guru",
"Wütende Mieze",
"Galgen",
"Müllhalde",
"Gartenhaus",
"Spraykanone",
"Zeitung",
"Verdammt in Saarbrücken",
"Großzügigkeit",
"Gentleman-Einbrecher",
"Ein Flicken und alles ist wie neu",
"Ghul",
"Ghul-Serum",
"Riesiger KVF",
"Riesige Ratte",
"Riesige Sandburg",
"Geschenkpaket",
"Gib mir was zu saufen oder es knallt!",
"Ruhm",
"Huldigt den Raben!",
"Angenagte Leiche",
"Alptraum der Traumlosen",
"Reicher Guru",
"Leichenhygieniker",
"Tomb Raider",
"Netter Kerl",
"Schaufenstergestalter",
"Meister der Schlüssel",
"Granatapfel",
"Rasierklingenmauer",
"Großer Architekt",
"Unabhängiger Großeinsiedler",
"Freimauer",
"Wassergraben",
"Großer Graben",
"Allmächtiger Schöpfer",
"Grüne Bierflasche",
"Grüner Kobold-Anzug",
"Makabre Bombe",
"Zeltplane",
"Bissiger Hund",
"Eimerhalter",
"Wächter-Turm",
"Wächter",
"Wächter - Gewinner des SoH",
"Guerilla",
"Wagemutiger Trapper",
"Medikamentetester",
"Waffengeschäft GunsnZombies",
"Wasserwaffen-Spezialist",
"Metallsäge",
"Angebissene Hähnchenflügel",
"Halloween",
"Hammam",
"Hand",
"Munitionsgriff",
"Handvoll Schrauben und Muttern",
"Eine Handvoll Bonbons",
"Schraubenschlüssel",
"Hängend",
"Freude der Stärke 8",
"Keine Macht den Drogen",
"Fröhlicher Hamster",
"Seuchenherd",
"Pandämonium ist meine Liebe!",
"Pandämonium? Hah. Einfach.",
"Gepanzerter Fakir",
"Schnellgebauter Tisch",
"Hast Du mal Feuer?",
"Er war Leber ...",
"Kopf",
"Schaufelführer",
"Bandagiert",
"Top in Form",
"Herz",
"Ich bin in der Hölle aufgewachsen.",
"Hölle, das esse ich jeden Morgen.",
"Hallo... ist da draußen jemand?",
"Hühnerstall",
"Held",
"Heldentafel",
"Heldentaten",
"Die Rückkehr des Helden",
"Hey! Willst du meine... Batterie sehen?",
"Hohepriesterin des Sonnentempels",
"Vorbild für das Volk",
"Haltet eure Position!",
"Nackt und Zerfleischt",
"Holy F***ing Iceberg",
"Heiliger Regen",
"Mein Haus",
"Baumarkt",
"Hobby-Heimwerker",
"Hausverbesserung",
"Hobbylabor",
"Hausarbeiten",
"Meser (halb Mensch, halb Malteser)",
"Drogenabhängig",
"Nervenkitzelsucher",
"Hospital-Bauplan (selten)",
"Hospital-Bauplan (ungewöhnlich)",
"Hospital-Bauplan (sehr selten!)",
"Heißluftballon",
"Hotel-Bauplan (selten)",
"Hotel-Bauplan (ungewöhnlich)",
"Hotel-Bauplan (sehr selten!)",
"Haus",
"Baracke",
"Dietrich",
"Zwei-Meter Schlange",
"Menschenfleisch",
"Spezialität",
"Kater",
"Hungriger Schakal",
"Hurlingstock",
"Hydraton 100mg",
"Wasserleitungsnetz",
"Hydraulik-Engineering",
"Schnitter der Aussenwelt",
"Ich bin ein Biest!",
"Ich bin ein Gott! Ich werde ewig leben!",
"Ich bin eine Legende",
"Ich beobachte euch...",
"Archi-Mädlicher Illustrator von Pi",
"Hey wir können die Zombies von hier oben sehen",
"Ich brauche niemanden",
"Ich sehe Alles!",
"Ich fresse Nägel und scheiße Kugeln!",
"Ich habe einen Plan",
"Ein Korn fehlt noch",
"Ich sehe überall Tote!",
"I see dead people 0_0",
"Ich koste alle meine Produkte",
"Solid Snake war gestern...",
"Ich gehe alleine.",
"Stadtallergie",
"Ich habe die Erde umrundet... zweimal!",
"Ich hab sogar das Klo abgesucht!",
"Ich habe Magenschmerzen...",
"Ein BMW? Kein Problem!",
"Alles unter 55% ist Wasser",
"Fleisch ist mein Gemüse",
"Hör auf mich, wenn du überleben möchtest",
"Yo, wir schaffen das!",
"Unleserliches Notizbuch",
"Erleuchteter Anführer",
"Ich glaube!",
"Neo",
"Mir ist schwindelig",
"Bob der Baumeister",
"Immunisiert",
"Unpersönliche Explodierende Fußmatte",
"Held der Community!",
"Ehemaliger Beta-Tester",
"Unvollständiger Kaffeekocher",
"Unvollständige Kettensäge",
"Unvollständiges Kartenspiel",
"Unglaubliche Entschlossenheit",
"Indianerfriedhof",
"Großer Löcherbuddler",
"Indiana Jones und die Ruinen der Aussenwelt",
"Infektion",
"Virenschleuder",
"Krankenstation",
"Schwere Verletzungen",
"Zweite Schicht",
"Gefräßiger Bürger",
"Sehr erfahrener Bürger",
"Betriebsanleitung",
"Beleidigendes Verhalten",
"Hekatoncheir",
"Innenarchitekt",
"Internet Explorer",
"Darmmelone",
"Irische Taschen sind prall gefüllt!",
"Schrankkoffer",
"Ist es ein Vogel? Ist es ein Flugzeug? Nein, es ist der super Batteriewerfer!",
"Es ist der Tod der mich fürchten sollte!",
"Es ist kleiner als im Katalog",
"Schmeckt am besten wenns noch schreit!",
"Es war wirklich zu einfach.",
"Bube",
"Gontran Happiness",
"Järpen-Tisch",
"Friedensstifter",
"Kanisterpumpe",
"Nur ein Finger",
"Vorbild für die Jugend",
"Kalaschni-Splash",
"Verrückter Skeptiker",
"Bewahrer der Freuden",
"Hortet zu viele Gegenstände",
"Wo klemmts?",
"König",
"Küche",
"Reparatur Fix",
"Laborratte",
"Ein Etikett",
"Maurerlehrling",
"Labyrinth",
"Labyrinth-Gollum",
"Große Truhe",
"Großer Vorhang",
"Großes Geschenkpaket",
"Großer Metallkoffer",
"Laserdiode",
"Die letzte Verteidigungslinie",
"Letzter Überlebender",
"Letzte Verteidigungslinie",
"Letzter Toter",
"Letzter Toter in einer Pandämoniumstadt",
"Automatiktür",
"Rasenmäher",
"Leckstopper",
"Umsichtiger Camper",
"Bein",
"Malteserzüchter",
"Außenweltlegende",
"Legendärer Dompteur",
"Legendäre Stadt",
"Bibliothekar",
"Licht in der Nacht",
"Leuchtturm",
"Höret meine Stimme",
"Leuchtender Kürbis",
"Kleine Zen-Fibel",
"Stadtmetzger",
"Wüstenstadt-Dealer",
"Türschloss",
"Heraklit der Außenwelt",
"Immer alles im Blick",
"Geplünderte Mall",
"Verirrte Seele",
"Messie der verlorenen Welt",
"Guru der Liebe",
"gering",
"LSD",
"Luzifers Tanzpartner",
"Glückspilz",
"Lucky 7",
"Schönes Fundstück",
"Jeffrey Dahmer",
"Mac Gyver der Außenwelt",
"Machete",
"Atomic Cafe",
"Magnet-Schlüssel",
"Abdruck vom Magnet-Schlüssel",
"Zone reinigen",
"Nagelbare Barrikade",
"Selbstgebaute Gitarre",
"Bringt Sachen ins Rollen!",
"Großer Wüstenkonditor",
"Ein Mann gegen die Außenwelt",
"Extra Tasche",
"Tipp-Ex",
"Karte",
"Meisterkoch der Sterne",
"Möbelgourmet",
"Martinet am Strand",
"Masochismus",
"Architekt (title)",
"Großer Baumeister",
"Cooking Mama",
"Höllenwächter",
"Meister der Nutzlosigkeit",
"Meister im Würmerfinden",
"Wüstenspringmaus",
"Meisterdieb",
"Meisterwerke in Gefahr",
"Matratze",
"Bürgermeister",
"Allein gegen die Horde",
"Fleischkäfig",
"Menschenfleischliebhaber",
"Knochen mit Fleisch",
"Bohrturm",
"Getriebe",
"Mitglied des Roten Kreuzes",
"Erinnerungen an die Zivilisation",
"Nachrichten",
"Metallkiste",
"Metallabfall",
"Verstärkende Balken",
"Metallstruktur",
"Minen",
"Mini Hi-Fi Anlage",
"Tante Emma Laden",
"Kleine Waffenschmiede",
"Bringt sich nicht genug ein",
"Ministerium für Sklaverei",
"Wasserkanone",
"Mobiltelefon",
"Obelisk der heutigen Zeit!",
"Money for Nothing",
"Verirrter Ausflügler",
"Stauraum",
"Motel Dusk",
"Motivierter Messebesucher",
"Autobahnraststätte",
"Verschimmelte Stulle",
"Verschimmelte Waffeln",
"Trümmerberg",
"Rundbrief",
"Brutalo",
"Mein Name ist Nobody",
"Mystic",
"Mystischer Trank",
"Mystic (job)",
"Lebender Mythos",
"Neil Armstrong der Außenwelt",
"Unkrautbekämpfungsmittel Ness-Quick",
"Geht kein Risiko ein",
"Sowas fasse ICH nicht an",
"Niemals ohne meinen Eimer",
"Wüstenausflüge",
"Tunnelratte",
"Nobler Spender",
"Noble Seele",
"Bauherr ohne Sinn und Verstand",
"Norden",
"Nordosten",
"Nordwesten",
"Absolut keine Angst!",
"Nie ohne meinen Hund!",
"MagLite Kinderlampe",
"Atombunker",
"Bei meiner Seel",
"Meine objekte",
"Altes Flugfeld",
"Alter Fahrradverleih",
"Alte Tür",
"Altes Feldkrankenhaus",
"Alte Hydraulikpumpe",
"Altes Polizeipräsidium",
"Santa Klaus ist Abfall",
"Alte Waschmaschine",
"Fallgruben",
"Allwissenheit",
"Räuberhöhle",
"Immer ein Auge offen",
"Wird in die Annalen eingehen",
"Eine Stadt sie zu knechten!",
"Offene Konservendose",
"Open-chakra",
"geöffnet",
"Angefangene Zigarettenschachtel",
"Abgelaufene Pims Kekse",
"Tüte mit labbrigen Chips",
"Kette + Vorhängeschloss",
"Schloss",
"Pandämonium",
"Paracetoid 7g",
"Paranoid",
"Ein Paket",
"Teilweise verrottet",
"Teilnehmende Stadt",
"Ein Patch, kein Spiel",
"Zusammengeschusterter Holzbalken",
"Lächerliches Taschenmesser",
"PC-Gehäuse",
"Bürgergericht",
"Dauermitglied in Mickys Club",
"Perser",
"Pharmazeutische Substanz",
"Phil Collins CD",
"Phoenix des Unterholzes",
"Fotoalbum",
"E-KEA",
"Taube aus der Unterwelt",
"Plünderer der Schnapsläden",
"Plünderer",
"Häuserplünderungen",
"Richtwert der Gemeinschaft",
"Rauchgranate Tannenduft",
"Wolfsfalle",
"Flugzeugwrack",
"Plastiktüte",
"Plastiktüte mit Sprengstoff",
"Blechplattenwerfer",
"Ich liebe den Geruch von gewaschenen Leichen am Morgen.",
"Aasgeier",
"Sperrholz",
"Praktischer Begleiter",
"Vibrator",
"Portal",
"Postfiliale",
"Wegelagerer post mortem",
"Kleiner Präparator",
"Fleischfetzen",
"Starke Seele",
"Kamera aus Vorkriegs-Tagen",
"Rechenmaschine",
"Hängt Santa Klaus!",
"Brezel",
"Erfahrener Junkie",
"Private Stadt",
"Proficamper",
"Profiwächter",
"Wunder",
"Produkttester",
"Pille palle, 3 Tage wach!",
"Beruf",
"Geistiger Beistand",
"Medium mit Preisnachlass",
"Straßenbeleuchtung",
"Meisterhafter Kochlöffelschwinger",
"Pumpe",
"Gereinigtes modriges Wasser",
"Druckregler PDTT Mark II",
"Arbeit ist Gesundheit",
"Gut erhaltener Holzscheit",
"Dame",
"Strahlender Bürger",
"Kassettenradio",
"RadioactiveMan",
"Radius Mark II",
"Zonenmarker Radius",
"Selbstgebaute Railgun",
"Rambos Großvater",
"Chef der Mauer",
"Ranzige Butterkekse",
"Gerankte Stadt",
"Wüstenwurmzüchter",
"Reaktor",
"Behausung wiederverwerten",
"Aktualisierung",
"Getrunken",
"Abonnent der Pandämoniumsauna",
"Tunnelblicker",
"Reinkarnator",
"Torpanzerung",
"Verstärkungen",
"Leichenentsorger",
"Großer Renovator",
"Reparaturset",
"Reparaturen",
"Rettung",
"Einfallsreichtum",
"Revolver",
"Schutzschild",
"Zerrissene rote Hose",
"Steinkanone",
"Rock n Roll HiFi",
"Schaukelstuhl",
"Textsammler",
"Anfängermodus",
"Verrotteter Baumstumpf",
"Abfallberg",
"Rucksack",
"Primitives Alarmsystem",
"Ruine",
"Gebäude erkunden",
"Grabungsleiter",
"Große rostige Kette",
"Fantomas",
"Expeditionssaboteur",
"Safe",
"Umzäuntes Haus",
"Freigiebiger Bürger",
"Sandball",
"Sandbälle! Yeah!",
"Schattenmann",
"Archäologe",
"Sandschloss",
"Sandmann",
"Sandy Maverick",
"Kreischender Rotor",
"Santa Klaus ist Abschaum",
"Santa Klaus ist ein Schummler",
"Santas Rentier",
"Erlöser der Menschheit",
"Sägemehlsteak",
"Scanner",
"Vogelscheuche",
"Buddler",
"Buddler - Gewinner des SoH",
"Schrödingers Box",
"Albi Supermarkt",
"Miezi? Jaaaa, komm her...",
"Aufklärer",
"Metalltrümmer",
"Kreischender Wecker",
"Kreischende Sägen",
"Schraubenzieher",
"Aufgewelltes Blatt",
"Versiegelter Architektenkoffer",
"Müll durchwühlen",
"Forschungsturm",
"Weitsichtig",
"Zweite Lunge",
"Zweite Lunge",
"Abgetragene rote Jacke",
"Sektenmitglied",
"Fund",
"Handelt zu egoistisch",
"Sprengstoff",
"Jagdmesser",
"Sesam, öffne dich...",
"Hütte",
"Ninja",
"ZomBIER Bar",
"Schamane",
"Blechplatte",
"Unverarbeitete Blechplatten",
"Sperrholzstück",
"Zerberus",
"Shock of heroes",
"Schießstand",
"Einkaufswagen",
"Dusche",
"Vorräte eines umsichtigen Bürgers",
"Verbannt",
"Ruheecke",
"Nein, das Ding fasse ich nicht an.",
"Polier",
"Einseifer",
"Schleuse",
"Kleines Cafe",
"Kleiner Friedhof",
"Holzzaun",
"Kleines Haus",
"Kleine Schaufel",
"Kleine Stadt",
"Kleiner Tribok",
"Rauch? Welcher Rauch?",
"Sandverkäufer",
"Wenn ich das nur vorher gewusst hätte...",
"Wo ich hinguck, seh ich Gegend.",
"Bingo",
"Samariter",
"Weicher Kürbis",
"Fingerschmied",
"Solide Holzplatte",
"Seelenknipser",
"Kernsammler (job)",
"Maurer aus Leidenschaft",
"Seele eines Profis",
"Kernsammler",
"Seelenverwerter",
"Seelenhändler",
"Beseelt",
"Süden",
"Südosten",
"Südwesten",
"Erinnerungsträger",
"Pik",
"Schweizer Taschenmesser",
"Gewürzte chinesische Nudeln",
"Pfahlgraben",
"Zackenmauer",
"Verteidigungspfähle",
"Spirituelles Wunder",
"Spiritueller Führer",
"Leichenwäscher",
"Leuchtrakete",
"St. Patrick",
"Blätterstapel",
"Großer trockener Stock",
"Eisengefäß mit modrigem Wasser",
"Pfahlwerfer",
"Fades Gebäck",
"Lebhafter Tribut",
"Statue des Raben",
"Schleimige Kugel",
"Entsorgungsfachmann",
"Übelriechendes Schwein",
"Eifriger Leser",
"Ein seltsames kreisförmiges Gerät",
"Starke Gewürze",
"Befestigte Unterkunft",
"Ein schöneres Leben",
"Außenweltschläfer",
"Super Soaker",
"Super-Flaum-Pulver",
"Werdender Superheld",
"Survivalbuch",
"Einsiedler",
"Einsiedler - Gewinner des SoH",
"Überlebende der Hölle!",
"Verdächtiger Traubensaft",
"Verdächtiges Gemüse",
"Schwedische Schreinerei",
"Süße Rache",
"Schweizer Taschenmesser",
"Bokors Guillotine",
"Tierliebhaber",
"Dompteur",
"Taser",
"Hausmannskost",
"Leckere Speise",
"Leckeres Steak",
"Wüstenphantom",
"Hennessy Highwayman",
"Maulheld",
"Techniker",
"Seele des Handwerks",
"Teddybär",
"Teleskop",
"Zelt",
"Außenweltreiseführer",
"Terraformingspezialist",
"Angststarre",
"Das braucht noch 10 Jahre!",
"Bank",
"Der Batterienator",
"Großer Umbau",
"Kleiner Schraubendreher",
"Pisa-Geraderichter",
"Arbeiterhelm und Kupferstiefel",
"Ein Wächter stirbt, aber gibt niemals auf",
"Kadaverentsorger",
"Menschliche Ameisenkolonie",
"Der unsichtbare Mann",
"Der letzte Überlebende",
"Truck Rathaus auf Rädern",
"Hans im Glück",
"Vernichter",
"Fels in der Brandung",
"Der Zweitletzte Mohikaner",
"Bar der verlorenen Hoffnungen",
"Ich sehe ein Blauuuuuuues Tal",
"Pfadfinder",
"Es ist Zeit für Kathedralen",
"Die Wahrheit ist irgendwo da draußen",
"Brunnen",
"Zahlreiche Diebstähle begangen",
"Diebstähle",
"Fleisch-Schuldner",
"Durazell",
"Ein Sternbild trägt meinen Namen",
"Dickflüssige Substanz",
"Dritte Schicht",
"Durst",
"Dieser Kobold ist unaufhaltbar.",
"Tausend-und-ein-Leben",
"MuadDib",
"Dreibeiniger Malteser",
"Für immer und seelich",
"Müdes Malteser Hündchen",
"Unermüdlicher Schrauber",
"Bis zur Unendlichkeit... und noch viel weiter!",
"Begrabener Freiwilliger",
"Loses Werkzeug",
"Werkzeugkiste",
"Fackel",
"Gequälte Seele",
"Wachturm",
"Stadt",
"Stadtbücherei",
"Meisterarchitekt",
"Spachtler",
"Bürgerbekleidung",
"Verbesserung des Tages",
"Toxin",
"Leiche eines Reisenden",
"Hinterhältigkeit",
"Holzbock",
"Vertrauenswürdiger Bürger",
"Verwegener Wanderer",
"Twinoid 500mg",
"Twinoid ist tabu",
"Krummes Holzbrett",
"Treffen der 4. Art",
"Wachsam",
"Groooße Mauer",
"Ultimate Fighter",
"Ultimativer Horden-Erkunder",
"Wüstenfuchs",
"Superpraktischer Rucksack",
"Gammler",
"Begnadeter Wüstenkonditor",
"Etikettenloses Medikament",
"Unidentifizierbare Trümmerstücke",
"Furchtloser Camper",
"Unförmige Zementblöcke",
"Undefinierbares Fleisch",
"Hier oben",
"Verbesserter Katapult",
"Verbesserte Karte",
"Gürtel mit Tasche",
"Beruhigungsspritze",
"Zerstäuber",
"Gemüsebeet",
"Ventilationssystem",
"Sehr überzeugender Pate",
"Giftfläschchen",
"Wildstyle Uppercut",
"Video Game Festival 2010",
"Videoprojektor",
"Hyäne",
"Verrückter Architekten-Visionär",
"Vodka Marinostov",
"Voodoo-Maske",
"Voodoo Sorceror",
"Wächt",
"Geldbündel",
"Wake The Dead",
"Verstärkte Stadtmauer",
"Weiterentwickelte Stadtmauer",
"Kerberos",
"Fast schon ein Zombie...",
"Holzbalkendrehkreuz",
"Lagerhalle",
"Wächter der Seelen",
"Stadtwächter",
"Nachtwächter",
"Wachturm",
"Wasserbombe",
"Wasserfänger",
"Wasserspender",
"Wasserfilter",
"Wasserkanonen",
"Wasserpistole",
"Kleinwasserkraftwerk",
"Wasserreiniger",
"Micropur Brausetablette",
"Ration Wasser",
"Wasserturm",
"Schwache Seele",
"Waffenabfall",
"Großer E-KEA Katalog",
"Westen",
"Timothy Leary",
"Wo ist mein Topf voll Gold, diebische Elster!",
"SM Spezialist",
"Soul Man",
"Wilde Bestie",
"Ich bändige Bestien",
"Nächtlicher Spaziergänger",
"Fortuna",
"Einarmiger Bandit",
"HAZ-Gewinner",
"Champions nehmen keine Drogen!",
"Guiness",
"Maschendrahtzaunstück",
"Drahtspule",
"Drogenabhängigkeit",
"Ohne Dach oder Leber",
"Zeuge der großen Verseuchung",
"Wunderwerke",
"Riesenrad",
"Wundervoll nutzlos",
"Wackliger Einkaufswagen",
"Holzabfall",
"Notfallabstützung",
"Zaun (Baustellen)",
"Werkstatt",
"Wurmfresser",
"Abgenutzte Kuriertasche",
"Verwundung - Arme",
"Verwundung - Auge",
"Verwundung - Fuß",
"Verwundung - Hände",
"Verwundung - Kopf",
"Verwundung - Bein",
"Umgekippter Laster",
"Alteisen",
"Voodoo-Puppe",
"Du kommst hier NICHT durch!",
"Dein Haus ist mein Haus",
"Camper im Jenseits",
"Hüter der Heiligen Batterie",
"Zombieliebling",
"Zombiereibe",
"Getötete Zombies",
"Zone"];
